Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2018-10, with the labels that each got.

#535 Experimental support for Panasonic A/C messages.
  examples/IRMQTTServer/IRMQTTServer.ino
  examples/IRrecvDumpV2/IRrecvDumpV2.ino
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.h
  src/IRutils.cpp
  src/ir_Panasonic.cpp
  src/ir_Panasonic.h
  test/Makefile
  test/ir_Panasonic_test.cpp
Labels: enhancement, hacktoberfest

#529 Samsung A/C fixes & improvements
  examples/IRMQTTServer/IRMQTTServer.ino
  src/IRrecv.cpp
  src/IRremoteESP8266.h
  src/ir_Samsung.cpp
  src/ir_Samsung.h
  test/Makefile
  test/ir_Samsung_test.cpp
Labels: Hacktoberfest, bug, enhancement

#538 Update tools/mkkeywords & keywords.txt
  keywords.txt
  tools/mkkeywords
Labels: Hacktoberfest, enhancement

#539 v2.5.1 release
  README.md
  ReleaseNotes.md
  library.json
  library.properties
  src/IRremoteESP8266.h
Labels: Hacktoberfest, enhancement

#542 Increase Panasonic A/C message tolerances.
  src/ir_Panasonic.cpp
  src/ir_Panasonic.h
  test/ir_Panasonic_test.cpp
Labels: Hacktoberfest, enhancement

#545 [BUG] Add missing send() method to IRPanasonicAC class.
  src/ir_Panasonic.cpp
Labels: Hacktoberfest, bug

#549 fix a few typos in docstrings
  tools/auto_analyse_raw_data.py
Labels: Hacktoberfest, enhancement

#553 Support for short Panasonic A/C messages.
  examples/IRrecvDumpV2/IRrecvDumpV2.ino
  src/IRrecv.cpp
  src/IRremoteESP8266.h
  src/ir_Panasonic.cpp
  src/ir_Panasonic.h
  test/ir_Panasonic_test.cpp
Labels: Hacktoberfest, enhancement

#552 Add support for a second LG protocol variant.
  examples/IRMQTTServer/IRMQTTServer.ino
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRutils.cpp
  src/ir_LG.cpp
  test/ir_LG_test.cpp
Labels: Hacktoberfest, enhancement

#554 Add support for Panasonic CKP series A/Cs.
  src/ir_Panasonic.cpp
  src/ir_Panasonic.h
  test/ir_Panasonic_test.cpp
Labels: enhancement

#558 Add missing sendWhirlpoolAC() to IRMQTTServer.ino
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: bug

#561 v2.5.2 release
  README.md
  ReleaseNotes.md
  keywords.txt
  library.json
  library.properties
  src/IRremoteESP8266.h
Labels: Hacktoberfest, enhancement

#562 Add missing '}' in output of Auto analyse.
  .gitignore
  tools/auto_analyse_raw_data.py
  tools/auto_analyse_raw_data_test.py
Labels: Hacktoberfest, enhancement
