Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2019-09, with the labels that each got.

#883 Teco: Add timer support.
  src/ir_Teco.cpp
  src/ir_Teco.h
  test/IRac_test.cpp
  test/ir_Teco_test.cpp
Labels: enhancement

#880 Add WebUI example sketch
  .github/Contributors.md
  examples/Web-AC-control/README.md
  examples/Web-AC-control/Web-AC-control.ino
  examples/Web-AC-control/printscreen.png
  examples/Web-AC-control/upload/favicon.ico
  examples/Web-AC-control/upload/level_1_off.svg
  examples/Web-AC-control/upload/level_1_on.svg
  examples/Web-AC-control/upload/level_2_off.svg
  examples/Web-AC-control/upload/level_2_on.svg
  examples/Web-AC-control/upload/level_3_off.svg
  examples/Web-AC-control/upload/level_3_on.svg
  examples/Web-AC-control/upload/level_4_off.svg
  examples/Web-AC-control/upload/level_4_on.svg
  examples/Web-AC-control/upload/ui.html
  examples/Web-AC-control/upload/ui.js
Labels: enhancement

#884 SamsungAc: Only send power on/off code if it's needed
  src/IRac.cpp
  src/IRac.h
  src/ir_Samsung.cpp
  src/ir_Samsung.h
  test/ir_Samsung_test.cpp
Labels: enhancement

#878 IRMQTTServer: Move from ArduinoJson v5 to v6
  .travis.yml
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
  examples/IRMQTTServer/platformio.ini
Labels: enhancement, question

#890 Basic support for Mitsubishi136 A/C protocol.
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRutils.cpp
  src/ir_Mitsubishi.cpp
  src/ir_Mitsubishi.h
  test/ir_Mitsubishi_test.cpp
Labels: enhancement

#896 [BUG] IRMQTTServer: Fix json climate state parsing.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: bug

#895 [Fujitsu] Add support for ARRY4 remote.
  src/IRac.cpp
  src/IRac.h
  src/ir_Fujitsu.cpp
  src/ir_Fujitsu.h
  test/IRac_test.cpp
  test/ir_Fujitsu_test.cpp
Labels: enhancement

#898 Mitsubishi136: Add detailed a/c support.
  src/IRac.cpp
  src/IRac.h
  src/ir_Mitsubishi.cpp
  src/ir_Mitsubishi.h
  test/IRac_test.cpp
  test/ir_Mitsubishi_test.cpp
Labels: enhancement

#886 Web-AC-control: Add platformio support files & Travis checks
  .travis.yml
  examples/Web-AC-control/Web-AC-control.ino
  examples/Web-AC-control/platformio.ini
Labels: enhancement

#906 auto_analyse_raw_data.py improvements
  tools/auto_analyse_raw_data.py
  tools/auto_analyse_raw_data_test.py
Labels: enhancement

#907 Fujitsu: Disable horiz swing for ARRY4
  src/ir_Fujitsu.cpp
Labels: enhancement

#904 Add test usage case for abusing Midea protocol.
  test/ir_Midea_test.cpp
Labels: wontfix

#914 MitsubishiAC: Improve decoding.
  src/ir_Mitsubishi.cpp
  src/ir_Mitsubishi.h
  test/ir_Mitsubishi_test.cpp
Labels: enhancement

#903 IRMQTTServer: Support for multiple climates.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
  src/ir_Mitsubishi.cpp
Labels: enhancement

#917 IRMQTTServer: Add option to clear retained settings.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: enhancement

#910 Daikin2: Corrections for common a/c interface.
  src/IRac.cpp
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  test/IRac_test.cpp
  test/ir_Daikin_test.cpp
Labels: bug, enhancement

#919 IRMQTTServer: Add flag & documentation for Home Assistant mode.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: enhancement

#923 PanasonicAc: Add better common a/c SwingV support.
  keywords.txt
  src/ir_Panasonic.cpp
  src/ir_Panasonic.h
  test/IRac_test.cpp
  test/ir_Panasonic_test.cpp
Labels: enhancement

#909 auto_analyse_raw_data: Experimental decode code generation.
  tools/auto_analyse_raw_data.py
  tools/auto_analyse_raw_data_test.py
Labels: enhancement

#924 Goodweather: Adjust timings & minor fixes.
  src/ir_Goodweather.cpp
  src/ir_Goodweather.h
  test/ir_Goodweather_test.cpp
Labels: enhancement

#913 Improve Common A/C api
  examples/CommonAcControl/CommonAcControl.ino
  src/IRac.cpp
  src/IRac.h
  src/ir_Samsung.cpp
  src/ir_Samsung.h
  test/IRac_test.cpp
Labels: enhancement

#928 Update IRMQTTServer to use latest API for common ac
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: enhancement

#920 More consistent `::toString()` output.
  src/IRutils.cpp
  src/ir_Amcor.cpp
  src/ir_Argo.cpp
  src/ir_Coolix.cpp
  src/ir_Daikin.cpp
  src/ir_Goodweather.cpp
  src/ir_Haier.cpp
  src/ir_Hitachi.cpp
  src/ir_Kelvinator.cpp
  src/ir_Mitsubishi.cpp
  src/ir_MitsubishiHeavy.cpp
  src/ir_Neoclima.cpp
  src/ir_Panasonic.cpp
  src/ir_Tcl.cpp
  src/ir_Whirlpool.cpp
  test/IRac_test.cpp
  test/ir_Amcor_test.cpp
  test/ir_Argo_test.cpp
  test/ir_Coolix_test.cpp
  test/ir_Daikin_test.cpp
  test/ir_Electra_test.cpp
  test/ir_Fujitsu_test.cpp
  test/ir_Goodweather_test.cpp
  test/ir_Gree_test.cpp
  test/ir_Haier_test.cpp
  test/ir_Hitachi_test.cpp
  test/ir_Kelvinator_test.cpp
  test/ir_Midea_test.cpp
  test/ir_MitsubishiHeavy_test.cpp
  test/ir_Mitsubishi_test.cpp
  test/ir_Neoclima_test.cpp
  test/ir_Panasonic_test.cpp
  test/ir_Samsung_test.cpp
  test/ir_Sharp_test.cpp
  test/ir_Tcl_test.cpp
  test/ir_Teco_test.cpp
  test/ir_Toshiba_test.cpp
  test/ir_Trotec_test.cpp
  test/ir_Vestel_test.cpp
  test/ir_Whirlpool_test.cpp
Labels: enhancement

#929 IRMQTTServer: Add TX channel support for HTTP interface.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: enhancement

#930 v2.6.6 release
  README.md
  ReleaseNotes.md
  SupportedProtocols.md
  examples/IRMQTTServer/IRMQTTServer.h
  keywords.txt
  library.json
  library.properties
  src/IRremoteESP8266.h
Labels: enhancement

#933 IRMQTTServer: Fix compile error when `MQTT_ENABLE` is false.
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: bug
