Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2019-04, with the labels that each got.

#658 Update Daikin2's Cool mode min temp to 18C
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  test/ir_Daikin_test.cpp
Labels: enhancement

#661 Add multiple independent GPIO sending support via MQTT.
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: enhancement

#663 Improve MQTT topic usage for feedback messages.
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: enhancement

#670 Add F() Macros
  src/IRutils.cpp
  src/ir_Coolix.cpp
  src/ir_Daikin.cpp
  src/ir_Fujitsu.cpp
  src/ir_Gree.cpp
  src/ir_Haier.cpp
  src/ir_Hitachi.cpp
  src/ir_Kelvinator.cpp
  src/ir_Midea.cpp
  src/ir_Mitsubishi.cpp
  src/ir_Panasonic.cpp
  src/ir_Samsung.cpp
  src/ir_Tcl.cpp
  src/ir_Teco.cpp
  src/ir_Toshiba.cpp
  src/ir_Vestel.cpp
  src/ir_Whirlpool.cpp
Labels: enhancement

#664 Initial prototype of a common interface for all A/Cs.
  src/IRac.cpp
  src/IRac.h
  src/IRsend.h
  src/IRtimer.cpp
  src/ir_Argo.cpp
  src/ir_Argo.h
  src/ir_Coolix.cpp
  src/ir_Coolix.h
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  src/ir_Fujitsu.cpp
  src/ir_Fujitsu.h
  src/ir_Gree.cpp
  src/ir_Gree.h
  src/ir_Haier.cpp
  src/ir_Haier.h
  src/ir_Hitachi.cpp
  src/ir_Hitachi.h
  src/ir_Kelvinator.cpp
  src/ir_Kelvinator.h
  src/ir_Midea.cpp
  src/ir_Midea.h
  src/ir_Mitsubishi.cpp
  src/ir_Mitsubishi.h
  src/ir_Panasonic.cpp
  src/ir_Panasonic.h
  src/ir_Samsung.cpp
  src/ir_Samsung.h
  src/ir_Tcl.cpp
  src/ir_Tcl.h
  src/ir_Teco.cpp
  src/ir_Teco.h
  src/ir_Toshiba.cpp
  src/ir_Toshiba.h
  src/ir_Trotec.cpp
  src/ir_Trotec.h
  src/ir_Vestel.cpp
  src/ir_Vestel.h
  src/ir_Whirlpool.cpp
  src/ir_Whirlpool.h
  test/IRac_test.cpp
  test/IRsend_test.h
  test/Makefile
  tools/Makefile
Labels: bug, enhancement

#665 First draft of support for Mitsubishi Heavy Industries A/Cs.
  .travis.yml
  examples/IRMQTTServer/IRMQTTServer.ino
  examples/IRrecvDumpV2/IRrecvDumpV2.ino
  examples/TurnOnMitsubishiHeavyAc/TurnOnMitsubishiHeavyAc.ino
  examples/TurnOnMitsubishiHeavyAc/platformio.ini
  src/IRac.cpp
  src/IRac.h
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.h
  src/IRutils.cpp
  src/ir_MitsubishiHeavy.cpp
  src/ir_MitsubishiHeavy.h
  test/IRac_test.cpp
  test/Makefile
  test/ir_MitsubishiHeavy_test.cpp
  tools/Makefile
Labels: enhancement

#674 Fix compile problem when DEBUG is defined.
  src/ir_MWM.cpp
Labels: bug

#677 Add advanced aircon/climate functionality to IRMQTTServer
  examples/IRMQTTServer/IRMQTTServer.ino
  examples/IRMQTTServer/platformio.ini
  src/IRac.cpp
  src/IRac.h
  src/IRremoteESP8266.h
  src/IRsend.h
  src/IRtimer.cpp
  src/IRtimer.h
  src/IRutils.cpp
  src/IRutils.h
  test/IRac_test.cpp
  test/IRutils_test.cpp
Labels: bug, enhancement

#679 Add Wifi filtering options to IRMQTTServer.
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: enhancement

#671 [BUG] Fix artificial vs. real state creation on HaierAC.
  src/ir_Haier.cpp
  test/ir_Haier_test.cpp
Labels: bug

#680 Move MQTT server connection parameters to WifiManager settings.
  .travis.yml
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
  examples/IRMQTTServer/platformio.ini
Labels: enhancement

#681 Implement htmlEscape() to prevent XSS etc.
  examples/IRMQTTServer/IRMQTTServer.ino
  src/IRutils.cpp
  src/IRutils.h
  test/IRutils_test.cpp
Labels: enhancement

#682 Add Home Assistant mqtt climate instructions.
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: enhancement

#685 Fix the byte array version of sendGree()
  src/ir_Gree.cpp
Labels: bug

#686 Adjust kGreeHdrSpace to 4500
  src/ir_Gree.cpp
  test/ir_Gree_test.cpp
Labels: enhancement

#678 DAIKIN/IRDaikinESP overhaul and add Comfort mode support.
  examples/IRMQTTServer/IRMQTTServer.ino
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.h
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  test/IRac_test.cpp
  test/ir_Daikin_test.cpp
Labels: bug, enhancement

#687 Add unit tests for Frequency and Duty cycle
  src/IRsend.cpp
  src/IRsend.h
  src/ir_LG.cpp
  test/IRac_test.cpp
  test/IRsend_test.cpp
  test/IRsend_test.h
  test/ir_Aiwa_test.cpp
  test/ir_Carrier_test.cpp
  test/ir_Coolix_test.cpp
  test/ir_Daikin_test.cpp
  test/ir_Denon_test.cpp
  test/ir_Dish_test.cpp
  test/ir_Electra_test.cpp
  test/ir_Fujitsu_test.cpp
  test/ir_GICable_test.cpp
  test/ir_GlobalCache_test.cpp
  test/ir_Gree_test.cpp
  test/ir_Haier_test.cpp
  test/ir_Hitachi_test.cpp
  test/ir_JVC_test.cpp
  test/ir_Kelvinator_test.cpp
  test/ir_LG_test.cpp
  test/ir_Lasertag_test.cpp
  test/ir_Lego_test.cpp
  test/ir_Lutron_test.cpp
  test/ir_MWM_test.cpp
  test/ir_Magiquest_test.cpp
  test/ir_Midea_test.cpp
  test/ir_Mitsubishi_test.cpp
  test/ir_NEC_test.cpp
  test/ir_Nikai_test.cpp
  test/ir_Panasonic_test.cpp
  test/ir_Pioneer_test.cpp
  test/ir_Pronto_test.cpp
  test/ir_RC5_RC6_test.cpp
  test/ir_RCMM_test.cpp
  test/ir_Samsung_test.cpp
  test/ir_Sanyo_test.cpp
  test/ir_Sharp_test.cpp
  test/ir_Sherwood_test.cpp
  test/ir_Sony_test.cpp
  test/ir_Teco_test.cpp
  test/ir_Toshiba_test.cpp
  test/ir_Vestel_test.cpp
  test/ir_Whirlpool_test.cpp
  test/ir_Whynter_test.cpp
Labels: bug, enhancement

#690 Experimental support for DAIKIN216 (ARC433B69)
  examples/IRMQTTServer/IRMQTTServer.ino
  examples/IRrecvDumpV2/IRrecvDumpV2.ino
  src/IRac.cpp
  src/IRac.h
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.h
  src/IRutils.cpp
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  test/IRac_test.cpp
  test/ir_Daikin_test.cpp
Labels: enhancement

#692 v2.6.0 release
  README.md
  ReleaseNotes.md
  examples/IRMQTTServer/IRMQTTServer.h
  keywords.txt
  library.json
  library.properties
  src/IRremoteESP8266.h
Labels: enhancement
