Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2019-06, with the labels that each got.

#721 Add function to convert decode_results to sendRaw() array.
  src/IRutils.cpp
  src/IRutils.h
  test/IRutils_test.cpp
Labels: enhancement

#723 IRMQTTServer: Add sequencing for sending MQTT IR commands.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
  examples/IRMQTTServer/platformio.ini
Labels: enhancement

#724 Update swing handling for Fujitsu A/Cs.
  src/IRac.cpp
  src/ir_Fujitsu.cpp
  test/IRac_test.cpp
  test/ir_Fujitsu_test.cpp
Labels: enhancement

#725 [BUG] Add missing on/off() to IRCoolixAC class.
  src/ir_Coolix.cpp
  src/ir_Coolix.h
  test/ir_Coolix_test.cpp
Labels: bug, enhancement

#735 Add `calibrate()` to all the A/C classes.
  src/ir_Argo.h
  src/ir_Coolix.h
  src/ir_Daikin.h
  src/ir_Fujitsu.h
  src/ir_Goodweather.h
  src/ir_Gree.h
  src/ir_Haier.h
  src/ir_Hitachi.h
  src/ir_Kelvinator.h
  src/ir_Midea.h
  src/ir_Mitsubishi.h
  src/ir_MitsubishiHeavy.h
  src/ir_Panasonic.h
  src/ir_Samsung.h
  src/ir_Sharp.h
  src/ir_Tcl.h
  src/ir_Toshiba.h
  src/ir_Trotec.h
  src/ir_Vestel.h
  src/ir_Whirlpool.h
Labels: enhancement

#737 Create example code for a Dumb IR repeater.
  examples/DumbIRRepeater/DumbIRRepeater.ino
  examples/DumbIRRepeater/platformio.ini
Labels: enhancement

#729 Add kPeriodOffset for CPU Freq of 160MHz.
  src/IRsend.h
Labels: enhancement

#736 [Fix] Correct set/getQuiet for Samsung A/C
  src/IRac.cpp
  src/ir_Samsung.cpp
  src/ir_Samsung.h
  test/IRac_test.cpp
  test/ir_Samsung_test.cpp
Labels: enhancement

#730 Add changable GPIO settings to IRMQTTServer.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: enhancement

#751 Fix travis enum34 issue.
  .travis.yml
Labels: enhancement

#753 Make supported device info more organised.
  src/ir_Aiwa.cpp
  src/ir_Argo.h
  src/ir_Carrier.cpp
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  src/ir_Denon.cpp
  src/ir_Dish.cpp
  src/ir_Electra.cpp
  src/ir_Fujitsu.h
  src/ir_GICable.cpp
  src/ir_GlobalCache.cpp
  src/ir_Goodweather.h
  src/ir_Gree.cpp
  src/ir_Gree.h
  src/ir_Haier.cpp
  src/ir_Haier.h
  src/ir_Hitachi.cpp
  src/ir_Hitachi.h
  src/ir_Inax.cpp
  src/ir_JVC.cpp
  src/ir_Kelvinator.cpp
  src/ir_Kelvinator.h
  src/ir_LG.cpp
  src/ir_LG.h
  src/ir_Lasertag.cpp
  src/ir_Lego.cpp
  src/ir_Lutron.cpp
  src/ir_MWM.cpp
  src/ir_Midea.cpp
  src/ir_Midea.h
  src/ir_Mitsubishi.cpp
  src/ir_Mitsubishi.h
  src/ir_MitsubishiHeavy.h
  src/ir_NEC.cpp
  src/ir_NEC.h
  src/ir_Nikai.cpp
  src/ir_Panasonic.cpp
  src/ir_Panasonic.h
  src/ir_Pioneer.cpp
  src/ir_Pronto.cpp
  src/ir_RC5_RC6.cpp
  src/ir_RCMM.cpp
  src/ir_Samsung.cpp
  src/ir_Samsung.h
  src/ir_Sanyo.cpp
  src/ir_Sharp.cpp
  src/ir_Sharp.h
  src/ir_Sherwood.cpp
  src/ir_Sony.cpp
  src/ir_Toshiba.cpp
  src/ir_Toshiba.h
  src/ir_Vestel.cpp
  src/ir_Vestel.h
  src/ir_Whirlpool.cpp
  src/ir_Whirlpool.h
  src/ir_Whynter.cpp
Labels: enhancement

#755 Scrape Supported Protocols and generate SupportedProtocols.md
  .gitignore
  .travis.yml
  .vscode/settings.json
  README.md
  SupportedProtocols.md
  src/ir_Gree.h
  src/ir_Haier.h
  src/ir_Hitachi.h
  src/ir_Kelvinator.h
  src/ir_LG.cpp
  src/ir_LG.h
  src/ir_Lego.cpp
  tools/Makefile
  tools/auto_analyse_raw_data.py
  tools/auto_analyse_raw_data_test.py
  tools/scrape_supported_devices.py
Labels: enhancement

#740 Add example code for a Smart(er) IR Repeater.
  .travis.yml
  examples/SmartIRRepeater/SmartIRRepeater.ino
  examples/SmartIRRepeater/platformio.ini
  src/IRsend.cpp
  src/IRsend.h
  src/ir_Daikin.cpp
  src/ir_Electra.cpp
  src/ir_Fujitsu.cpp
  src/ir_Gree.cpp
  src/ir_Kelvinator.cpp
  src/ir_MWM.cpp
  src/ir_Mitsubishi.cpp
  test/IRsend_test.cpp
Labels: enhancement

#742 Initial support for the ESP32 architecture & boards.
  .github/Contributors.md
  .github/issue_template.md
  README.md
  examples/ControlSamsungAC/platformio.ini
  examples/DumbIRRepeater/platformio.ini
  examples/IRGCSendDemo/platformio.ini
  examples/IRGCTCPServer/IRGCTCPServer.ino
  examples/IRGCTCPServer/platformio.ini
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
  examples/IRMQTTServer/platformio.ini
  examples/IRServer/IRServer.ino
  examples/IRServer/platformio.ini
  examples/IRrecvDemo/platformio.ini
  examples/IRrecvDump/platformio.ini
  examples/IRrecvDumpV2/IRrecvDumpV2.ino
  examples/IRrecvDumpV2/platformio.ini
  examples/IRsendDemo/IRsendDemo.ino
  examples/IRsendDemo/platformio.ini
  examples/IRsendProntoDemo/platformio.ini
  examples/JVCPanasonicSendDemo/platformio.ini
  examples/LGACSend/platformio.ini
  examples/TurnOnArgoAC/platformio.ini
  examples/TurnOnDaikinAC/platformio.ini
  examples/TurnOnFujitsuAC/platformio.ini
  examples/TurnOnKelvinatorAC/platformio.ini
  examples/TurnOnMitsubishiAC/platformio.ini
  examples/TurnOnMitsubishiHeavyAc/platformio.ini
  examples/TurnOnPanasonicAC/platformio.ini
  examples/TurnOnToshibaAC/platformio.ini
  examples/TurnOnTrotecAC/platformio.ini
  library.json
  library.properties
  platformio.ini
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRsend.h
Labels: enhancement

#756 Fix compiler warning in IRutils_test.cpp
  test/IRutils_test.cpp
Labels: enhancement

#754 Basic DAIKIN 160bit send and decode.
  examples/IRMQTTServer/IRMQTTServer.ino
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.h
  src/IRutils.cpp
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  test/ir_Daikin_test.cpp
Labels: enhancement

#757 Add `DAIKIN160` to `IRsend::send()`
  src/IRsend.cpp
Labels: bug

#745 Increase tolerance value for TCL112AC protocol.
  src/ir_Tcl.cpp
  src/ir_Tcl.h
  test/ir_Tcl_test.cpp
Labels: enhancement

#749 IRMQTTServer: Add some memory alloc safety checks.
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: enhancement

#752 IRMQTTServer: Enforce a repeat for all Coolix calls
  SupportedProtocols.md
  examples/IRMQTTServer/IRMQTTServer.ino
  src/IRremoteESP8266.h
  src/ir_Coolix.cpp
  src/ir_Coolix.h
  test/IRac_test.cpp
Labels: enhancement

#759 v2.6.2 release
  README.md
  ReleaseNotes.md
  SupportedProtocols.md
  examples/IRMQTTServer/IRMQTTServer.h
  keywords.txt
  library.json
  library.properties
  src/IRremoteESP8266.h
Labels: enhancement

#763 IRMQTTServer: Allow sending/receiving climate via JSON over MQTT.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
  src/IRac.cpp
  src/IRutils.cpp
Labels: enhancement

#765 Refactor to use generic decode routines in `IRrecv` class.
  src/IRrecv.cpp
  src/IRrecv.h
  src/ir_Argo.cpp
  src/ir_Carrier.cpp
  src/ir_Coolix.cpp
  src/ir_Coolix.h
  src/ir_Daikin.cpp
  src/ir_Denon.cpp
  src/ir_Dish.cpp
  src/ir_Electra.cpp
  src/ir_GICable.cpp
  src/ir_Gree.cpp
  src/ir_Haier.cpp
  src/ir_Hitachi.cpp
  src/ir_Inax.cpp
  src/ir_JVC.cpp
  src/ir_Kelvinator.cpp
  src/ir_Lego.cpp
  src/ir_Midea.cpp
  src/ir_Mitsubishi.cpp
  src/ir_MitsubishiHeavy.cpp
  src/ir_NEC.cpp
  src/ir_Nikai.cpp
  src/ir_Panasonic.cpp
  src/ir_Pioneer.cpp
  src/ir_Samsung.cpp
  src/ir_Sharp.cpp
  src/ir_Tcl.cpp
  src/ir_Teco.cpp
  src/ir_Toshiba.cpp
  src/ir_Trotec.cpp
  src/ir_Vestel.cpp
  src/ir_Whirlpool.cpp
  src/ir_Whynter.cpp
  test/IRrecv_test.cpp
Labels: enhancement

#766 Improve `mkkeywords` tool.
  keywords.txt
  tools/mkkeywords
Labels: enhancement

#760 Add supported model info for Tcl a/c
  SupportedProtocols.md
  src/ir_Tcl.h
Labels: enhancement

#770 IR AC Gree: add WiFi and IFeel bits
  SupportedProtocols.md
  src/ir_Gree.cpp
  src/ir_Gree.h
  test/IRac_test.cpp
  test/ir_Gree_test.cpp
Labels: enhancement

#774 [BUG] Ensure `IRrecv`'s GPIO is set to input mode.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
  src/IRrecv.cpp
  src/IRrecv.h
Labels: bug

#767 Experimental detailed support for Neoclima protocol.
  SupportedProtocols.md
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
  examples/IRrecvDumpV2/IRrecvDumpV2.ino
  keywords.txt
  src/IRac.cpp
  src/IRac.h
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRutils.cpp
  src/ir_Neoclima.cpp
  src/ir_Neoclima.h
  test/IRac_test.cpp
  test/Makefile
  test/ir_Neoclima_test.cpp
  test/ir_Panasonic_test.cpp
  test/ir_Samsung_test.cpp
  tools/Makefile
Labels: enhancement

#773 Add sanity tests for unexpected conditions in IRrecv.
  src/IRrecv.cpp
  src/ir_Sony.cpp
  test/ir_Sony_test.cpp
Labels: bug, enhancement

#779 GREE: Improve IFeel & WiFi unit tests
  src/ir_Gree.h
  test/ir_Gree_test.cpp
Labels: enhancement
