Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2019-11, with the labels that each got.

#987 Fix Incorrect Hitachi424Ac Power Byte Values
  src/ir_Hitachi.cpp
  src/ir_Hitachi.h
  test/ir_Hitachi_test.cpp
Labels: bug, enhancement

#990 Coolix: Fix setPower(false) issue.
  src/ir_Coolix.cpp
  test/ir_Coolix_test.cpp
Labels: bug

#986 Add Vertical Swing ability for Hitachi424Ac
  src/IRac.cpp
  src/IRac.h
  src/ir_Hitachi.cpp
  src/ir_Hitachi.h
  test/IRac_test.cpp
  test/ir_Hitachi_test.cpp
Labels: enhancement

#992 Use `char*` instead of `String` for common text.
  src/IRac.cpp
  src/IRtext.cpp
  src/IRtext.h
  src/IRutils.cpp
  src/ir_Argo.cpp
  src/ir_Coolix.cpp
  src/ir_Daikin.cpp
  src/ir_Fujitsu.cpp
  src/ir_Goodweather.cpp
  src/ir_Gree.cpp
  src/ir_Haier.cpp
  src/ir_Hitachi.cpp
  src/ir_Midea.cpp
  src/ir_Mitsubishi.cpp
  src/ir_MitsubishiHeavy.cpp
  src/ir_Vestel.cpp
  src/ir_Whirlpool.cpp
  test/Makefile
  tools/generate_irtext_h.sh
Labels: enhancement

#993 Move newly added common text to a better location.
  src/IRtext.cpp
  src/locale/defaults.h
Labels: enhancement

#995 IRMQTTServer: Update HA example/discovery message.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: enhancement

#998 v2.7.1 release
  README.md
  README_fr.md
  ReleaseNotes.md
  SupportedProtocols.md
  keywords.txt
  library.json
  library.properties
  src/IRremoteESP8266.h
Labels: enhancement
