Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2019-10, with the labels that each got.

#935 Grammar Corrections
  README.md
Labels: Hacktoberfest

#938 Fix compile issue on ESP32 platform.
  examples/IRsendProntoDemo/IRsendProntoDemo.ino
Labels: ESP32, bug

#936 Port CI pipeline to PlatformIO
  .travis.yml
Labels: Hacktoberfest, enhancement

#939 Remove unneeded Travis `pio` command.
  .travis.yml
Labels: enhancement

#940 Improve generation of list of pio projects.
  .travis.yml
Labels: Hacktoberfest, enhancement

#941 Fixed Coolix kCoolixDefaultState (file Update ir_Coolix.h)
  src/ir_Coolix.h
  test/ir_Coolix_test.cpp
Labels: Hacktoberfest, enhancement

#948 Create de_DE.h
  src/locale/de_DE.h
Labels: enhancement

#949 Create de_CH locale
  src/locale/de_CH.h
Labels: Hacktoberfest, enhancement

#950 Update de_DE.h
  src/locale/de_DE.h
Labels: Hacktoberfest, enhancement

#951 Remove duplicate
  src/locale/defaults.h
Labels: Hacktoberfest, enhancement

#934 Refactor to use common routines/macros to handle bit manipulation.
  keywords.txt
  src/IRutils.cpp
  src/IRutils.h
  src/ir_Amcor.cpp
  src/ir_Amcor.h
  src/ir_Argo.cpp
  src/ir_Argo.h
  src/ir_Coolix.cpp
  src/ir_Coolix.h
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  src/ir_Electra.cpp
  src/ir_Electra.h
  src/ir_Fujitsu.cpp
  src/ir_Fujitsu.h
  src/ir_Goodweather.cpp
  src/ir_Goodweather.h
  src/ir_Gree.cpp
  src/ir_Gree.h
  src/ir_Haier.cpp
  src/ir_Haier.h
  src/ir_Hitachi.cpp
  src/ir_Hitachi.h
  src/ir_Kelvinator.cpp
  src/ir_Midea.cpp
  src/ir_Midea.h
  src/ir_Mitsubishi.cpp
  src/ir_Mitsubishi.h
  src/ir_MitsubishiHeavy.cpp
  src/ir_MitsubishiHeavy.h
  src/ir_Neoclima.cpp
  src/ir_Neoclima.h
  src/ir_Panasonic.cpp
  src/ir_Panasonic.h
  src/ir_Samsung.cpp
  src/ir_Samsung.h
  src/ir_Sharp.cpp
  src/ir_Sharp.h
  src/ir_Tcl.cpp
  src/ir_Tcl.h
  src/ir_Teco.cpp
  src/ir_Teco.h
  src/ir_Toshiba.cpp
  src/ir_Toshiba.h
  src/ir_Trotec.cpp
  src/ir_Trotec.h
  src/ir_Vestel.cpp
  src/ir_Vestel.h
  src/ir_Whirlpool.cpp
  src/ir_Whirlpool.h
  test/IRac_test.cpp
  test/IRutils_test.cpp
  test/Makefile
  test/ir_Argo_test.cpp
  test/ir_Haier_test.cpp
  test/ir_MitsubishiHeavy_test.cpp
  test/ir_Mitsubishi_test.cpp
  test/ir_Panasonic_test.cpp
Labels: Hacktoberfest, enhancement

#952 Update de_DE.h to complete translation
  src/locale/de_DE.h
Labels: Hacktoberfest, enhancement

#953 Create es_ES.h
  src/locale/es_ES.h
Labels: Hacktoberfest, enhancement

#954 Update de_CH.h
  src/locale/de_CH.h
Labels: Hacktoberfest, enhancement

#956 Update README.md
  README.md
Labels: Hacktoberfest, enhancement

#955 Minor i18n changes and add some platformio environs.
  examples/CommonAcControl/platformio.ini
  examples/ControlSamsungAC/platformio.ini
  examples/DumbIRRepeater/platformio.ini
  examples/IRGCSendDemo/platformio.ini
  examples/IRGCTCPServer/platformio.ini
  examples/IRMQTTServer/platformio.ini
  examples/IRServer/platformio.ini
  examples/IRrecvDemo/platformio.ini
  examples/IRrecvDump/platformio.ini
  examples/IRrecvDumpV2/IRrecvDumpV2.ino
  examples/IRrecvDumpV2/platformio.ini
  examples/IRsendDemo/platformio.ini
  examples/IRsendProntoDemo/platformio.ini
  examples/JVCPanasonicSendDemo/platformio.ini
  examples/LGACSend/platformio.ini
  examples/SmartIRRepeater/platformio.ini
  examples/TurnOnArgoAC/platformio.ini
  examples/TurnOnDaikinAC/platformio.ini
  examples/TurnOnFujitsuAC/platformio.ini
  examples/TurnOnKelvinatorAC/platformio.ini
  examples/TurnOnMitsubishiAC/platformio.ini
  examples/TurnOnMitsubishiHeavyAc/platformio.ini
  examples/TurnOnPanasonicAC/platformio.ini
  examples/TurnOnToshibaAC/platformio.ini
  examples/TurnOnTrotecAC/platformio.ini
  examples/Web-AC-control/platformio.ini
  platformio.ini
  src/IRremoteESP8266.h
  src/i18n.h
  src/locale/de-CH.h
  src/locale/de-DE.h
  src/locale/defaults.h
  src/locale/en-AU.h
  src/locale/en-IE.h
  src/locale/en-UK.h
  src/locale/en-US.h
  src/locale/es-ES.h
  test/Makefile
  tools/Makefile
Labels: Hacktoberfest, enhancement

#957 Make travis checks faster.
  .travis.yml
  examples/CommonAcControl/platformio.ini
  examples/ControlSamsungAC/platformio.ini
  examples/DumbIRRepeater/platformio.ini
  examples/IRGCSendDemo/platformio.ini
  examples/IRGCTCPServer/platformio.ini
  examples/IRMQTTServer/platformio.ini
  examples/IRServer/platformio.ini
  examples/IRrecvDemo/platformio.ini
  examples/IRrecvDump/platformio.ini
  examples/IRrecvDumpV2/platformio.ini
  examples/IRsendDemo/platformio.ini
  examples/IRsendProntoDemo/platformio.ini
  examples/JVCPanasonicSendDemo/platformio.ini
  examples/LGACSend/platformio.ini
  examples/SmartIRRepeater/platformio.ini
  examples/TurnOnArgoAC/platformio.ini
  examples/TurnOnDaikinAC/platformio.ini
  examples/TurnOnFujitsuAC/platformio.ini
  examples/TurnOnKelvinatorAC/platformio.ini
  examples/TurnOnMitsubishiAC/platformio.ini
  examples/TurnOnMitsubishiHeavyAc/platformio.ini
  examples/TurnOnPanasonicAC/platformio.ini
  examples/TurnOnToshibaAC/platformio.ini
  examples/TurnOnTrotecAC/platformio.ini
  examples/Web-AC-control/platformio.ini
  platformio.ini
Labels: enhancement

#959 translate README in french
  README_fr.md
Labels: Hacktoberfest, enhancement

#963 Adding Support for Decoding codes in raw code format in gc_decode tool
  tools/Makefile
  tools/gc_decode.cpp
Labels: Hacktoberfest, enhancement

#962 Create fr-FR.h
  src/locale/fr-FR.h
Labels: Hacktoberfest, enhancement

#966 Improve i18n text.
  examples/IRrecvDumpV2/platformio.ini
  src/IRtext.cpp
  src/IRtext.h
  src/ir_Daikin.cpp
  src/locale/de-DE.h
  src/locale/defaults.h
  src/locale/en-US.h
  src/locale/es-ES.h
  src/locale/fr-FR.h
  test/IRac_test.cpp
  test/Makefile
  test/ir_Daikin_test.cpp
  tools/Makefile
Labels: enhancement

#967 A/C setRaw/getRaw/stateReset() cleanup.
  src/ir_Amcor.cpp
  src/ir_Argo.cpp
  src/ir_Daikin.cpp
  src/ir_Electra.cpp
  src/ir_Gree.cpp
  src/ir_Haier.cpp
  src/ir_Hitachi.cpp
  src/ir_Kelvinator.cpp
  src/ir_Mitsubishi.cpp
  src/ir_MitsubishiHeavy.cpp
  src/ir_Neoclima.cpp
  src/ir_Panasonic.cpp
  src/ir_Samsung.cpp
  src/ir_Sharp.cpp
  src/ir_Tcl.cpp
  src/ir_Toshiba.cpp
  src/ir_Trotec.cpp
  src/ir_Whirlpool.cpp
Labels: enhancement

#947 Mitsubishi 112
  .github/Contributors.md
  src/IRac.cpp
  src/IRac.h
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRutils.cpp
  src/ir_Mitsubishi.cpp
  src/ir_Mitsubishi.h
  src/ir_Tcl.cpp
  src/ir_Tcl.h
  test/ir_Mitsubishi_test.cpp
Labels: Hacktoberfest, enhancement

#971 Experimental detailed support for DAIKIN152
  src/IRac.cpp
  src/IRac.h
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  test/IRac_test.cpp
  test/Makefile
  test/ir_Daikin_test.cpp
Labels: enhancement

#968 Cleanup new Mitsubishi(112) A/C code.
  src/IRac.cpp
  src/ir_Mitsubishi.cpp
  src/ir_Mitsubishi.h
  test/ir_Mitsubishi_test.cpp
Labels: Hacktoberfest, enhancement

#976 [Bug] Fix > 64 bit send code generation.
  tools/auto_analyse_raw_data.py
  tools/auto_analyse_raw_data_test.py
Labels: Hacktoberfest, bug

#944 Coolix improvements
  src/IRac.cpp
  src/ir_Coolix.cpp
  src/ir_Coolix.h
  test/ir_Coolix_test.cpp
Labels: Hacktoberfest, enhancement

#975 Basic support for Hitachi 424 bit protocol.
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRutils.cpp
  src/ir_Hitachi.cpp
  src/ir_Hitachi.h
  test/ir_Hitachi_test.cpp
Labels: Hacktoberfest, enhancement

#977 auto_analyse: Generate better code when a Leader is detected.
  tools/auto_analyse_raw_data.py
  tools/auto_analyse_raw_data_test.py
Labels: Hacktoberfest, enhancement

#981 Add Hitiachi424 common a/c support.
  src/IRac.cpp
  src/IRac.h
  src/ir_Daikin.cpp
  src/ir_Hitachi.cpp
  src/ir_Hitachi.h
  test/IRac_test.cpp
  test/ir_Hitachi_test.cpp
Labels: enhancement

#982 Update decodeToState()
  src/IRac.cpp
Labels: bug, enhancement

#983 v2.7.0 Release
  README.md
  README_fr.md
  ReleaseNotes.md
  SupportedProtocols.md
  keywords.txt
  library.json
  library.properties
  src/IRremoteESP8266.h
Labels: Hacktoberfest, enhancement
