Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2019-07, with the labels that each got.

#793 Split travis CI into three jobs
  .travis.yml
Labels: enhancement

#777 Daikin160: Add detailed & common a/c support.
  examples/IRMQTTServer/IRMQTTServer.ino
  examples/IRrecvDumpV2/IRrecvDumpV2.ino
  src/IRac.cpp
  src/IRac.h
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  test/IRac_test.cpp
  test/ir_Daikin_test.cpp
Labels: enhancement

#782 Refactor A/C toString()'s to reduce code size. Saves 3.5K.
  src/IRutils.cpp
  src/IRutils.h
  src/ir_Argo.cpp
  src/ir_Coolix.cpp
  src/ir_Daikin.cpp
  src/ir_Fujitsu.cpp
  src/ir_Goodweather.cpp
  src/ir_Gree.cpp
  src/ir_Haier.cpp
  src/ir_Hitachi.cpp
  src/ir_Kelvinator.cpp
  src/ir_Midea.cpp
  src/ir_Mitsubishi.cpp
  src/ir_MitsubishiHeavy.cpp
  src/ir_Panasonic.cpp
  src/ir_Samsung.cpp
  src/ir_Sharp.cpp
  src/ir_Tcl.cpp
  src/ir_Teco.cpp
  src/ir_Toshiba.cpp
  src/ir_Trotec.cpp
  src/ir_Vestel.cpp
  src/ir_Whirlpool.cpp
  test/IRac_test.cpp
  test/ir_Haier_test.cpp
  test/ir_MitsubishiHeavy_test.cpp
  test/ir_Mitsubishi_test.cpp
Labels: enhancement

#784 [BUG] IRMQTTServer: REPLAY_DECODED_AC_MESSAGE not working.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: bug, enhancement

#792 Change `ControlSamsungAC` example to not use `sendExtended()`
  examples/ControlSamsungAC/ControlSamsungAC.ino
  src/ir_Samsung.cpp
  src/ir_Samsung.h
Labels: bug, enhancement

#790 Reduce example code size and complexity
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
  examples/IRrecvDumpV2/IRrecvDumpV2.ino
  src/IRac.cpp
  src/IRac.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRutils.cpp
  test/IRac_test.cpp
  test/IRsend_test.cpp
  test/IRutils_test.cpp
Labels: enhancement

#788 Experimental detailed support for Electra/AUX protocol
  examples/IRMQTTServer/IRMQTTServer.ino
  src/IRac.cpp
  src/IRac.h
  src/IRremoteESP8266.h
  src/ir_Electra.cpp
  src/ir_Electra.h
  test/IRac_test.cpp
  test/Makefile
  test/ir_Electra_test.cpp
  tools/Makefile
Labels: enhancement

#795 Show available sketch space for OTA uploads.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
  examples/IRMQTTServer/platformio.ini
Labels: enhancement

#797 Additional fix for `REPLAY_DECODED_AC_MESSAGE`
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: bug

#799 v2.6.3 release
  README.md
  ReleaseNotes.md
  SupportedProtocols.md
  examples/IRMQTTServer/IRMQTTServer.h
  keywords.txt
  library.json
  library.properties
  src/IRremoteESP8266.h
  src/IRutils.cpp
  tools/mkkeywords
Labels: enhancement

#801 Move `htmlEscape()` to the IRutils namespace
  examples/IRMQTTServer/IRMQTTServer.ino
  src/IRutils.cpp
  src/IRutils.h
  test/IRutils_test.cpp
Labels: enhancement

#811 [Bug] IRMQTTServer: Fix sending >64 bit codes.
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: bug

#812 Update platformio.ini files for PlatformIO v4.0.0
  examples/ControlSamsungAC/platformio.ini
  examples/DumbIRRepeater/platformio.ini
  examples/IRGCSendDemo/platformio.ini
  examples/IRGCTCPServer/platformio.ini
  examples/IRMQTTServer/platformio.ini
  examples/IRServer/platformio.ini
  examples/IRrecvDemo/platformio.ini
  examples/IRrecvDump/platformio.ini
  examples/IRrecvDumpV2/platformio.ini
  examples/IRsendDemo/platformio.ini
  examples/IRsendProntoDemo/platformio.ini
  examples/JVCPanasonicSendDemo/platformio.ini
  examples/LGACSend/platformio.ini
  examples/SmartIRRepeater/platformio.ini
  examples/TurnOnArgoAC/platformio.ini
  examples/TurnOnDaikinAC/platformio.ini
  examples/TurnOnFujitsuAC/platformio.ini
  examples/TurnOnKelvinatorAC/platformio.ini
  examples/TurnOnMitsubishiAC/platformio.ini
  examples/TurnOnMitsubishiHeavyAc/platformio.ini
  examples/TurnOnPanasonicAC/platformio.ini
  examples/TurnOnToshibaAC/platformio.ini
  examples/TurnOnTrotecAC/platformio.ini
  platformio.ini
Labels: enhancement

#808 Add setting of output options to A/C classes.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
  src/IRac.cpp
  src/IRac.h
  src/ir_Argo.cpp
  src/ir_Argo.h
  src/ir_Coolix.cpp
  src/ir_Coolix.h
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  src/ir_Electra.cpp
  src/ir_Electra.h
  src/ir_Fujitsu.cpp
  src/ir_Fujitsu.h
  src/ir_Goodweather.cpp
  src/ir_Goodweather.h
  src/ir_Gree.cpp
  src/ir_Gree.h
  src/ir_Haier.cpp
  src/ir_Haier.h
  src/ir_Hitachi.cpp
  src/ir_Hitachi.h
  src/ir_Kelvinator.cpp
  src/ir_Kelvinator.h
  src/ir_Midea.cpp
  src/ir_Midea.h
  src/ir_Mitsubishi.cpp
  src/ir_Mitsubishi.h
  src/ir_MitsubishiHeavy.cpp
  src/ir_MitsubishiHeavy.h
  src/ir_Neoclima.cpp
  src/ir_Neoclima.h
  src/ir_Panasonic.cpp
  src/ir_Panasonic.h
  src/ir_Samsung.cpp
  src/ir_Samsung.h
  src/ir_Sharp.cpp
  src/ir_Sharp.h
  src/ir_Tcl.cpp
  src/ir_Tcl.h
  src/ir_Teco.cpp
  src/ir_Teco.h
  src/ir_Toshiba.cpp
  src/ir_Toshiba.h
  src/ir_Trotec.cpp
  src/ir_Trotec.h
  src/ir_Vestel.cpp
  src/ir_Vestel.h
  src/ir_Whirlpool.cpp
  src/ir_Whirlpool.h
Labels: enhancement

#816 Experimental detailed support for Daikin 176 bits
  src/IRac.cpp
  src/IRac.h
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRutils.cpp
  src/ir_Daikin.cpp
  src/ir_Daikin.h
Labels: enhancement

#825 Coolix: Better `toCommon()` support.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
  src/IRac.cpp
  src/IRac.h
  src/ir_Coolix.cpp
  src/ir_Coolix.h
  test/IRac_test.cpp
Labels: bug, enhancement

#813 Reduce duplicate code to save space.
  examples/IRMQTTServer/IRMQTTServer.ino
  src/IRutils.cpp
  src/IRutils.h
  src/ir_Argo.cpp
  src/ir_Coolix.cpp
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  src/ir_Electra.cpp
  src/ir_Fujitsu.cpp
  src/ir_Goodweather.cpp
  src/ir_Gree.cpp
  src/ir_Gree.h
  src/ir_Haier.cpp
  src/ir_Haier.h
  src/ir_Hitachi.cpp
  src/ir_Hitachi.h
  src/ir_Kelvinator.cpp
  src/ir_Kelvinator.h
  src/ir_Midea.cpp
  src/ir_Mitsubishi.cpp
  src/ir_Mitsubishi.h
  src/ir_MitsubishiHeavy.cpp
  src/ir_Neoclima.cpp
  src/ir_Panasonic.cpp
  src/ir_Panasonic.h
  src/ir_Samsung.cpp
  src/ir_Sharp.cpp
  src/ir_Sharp.h
  src/ir_Tcl.cpp
  src/ir_Teco.cpp
  src/ir_Toshiba.cpp
  src/ir_Toshiba.h
  src/ir_Trotec.cpp
  src/ir_Vestel.cpp
  src/ir_Whirlpool.cpp
  src/ir_Whirlpool.h
  test/IRac_test.cpp
  test/IRutils_test.cpp
  test/ir_Daikin_test.cpp
  test/ir_Fujitsu_test.cpp
  test/ir_Goodweather_test.cpp
  test/ir_Gree_test.cpp
  test/ir_Haier_test.cpp
  test/ir_Hitachi_test.cpp
  test/ir_Kelvinator_test.cpp
  test/ir_Midea_test.cpp
  test/ir_Mitsubishi_test.cpp
  test/ir_Panasonic_test.cpp
  test/ir_Samsung_test.cpp
  test/ir_Sharp_test.cpp
  test/ir_Teco_test.cpp
  test/ir_Toshiba_test.cpp
  test/ir_Trotec_test.cpp
  test/ir_Vestel_test.cpp
  test/ir_Whirlpool_test.cpp
Labels: enhancement

#828 Initial support for Daikin 17 Series/BRC52B63
  SupportedProtocols.md
  examples/IRMQTTServer/IRMQTTServer.ino
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRutils.cpp
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  test/ir_Daikin_test.cpp
Labels: enhancement

#830 Fix sendPioneer with Pioneer specific timings
  src/ir_NEC.cpp
  src/ir_Pioneer.cpp
  test/ir_Pioneer_test.cpp
Labels: enhancement

#829 [BUG] Fix parameters for coolix in IRac::sendAc()
  src/IRac.cpp
  src/ir_Coolix.cpp
  test/IRac_test.cpp
  test/ir_Coolix_test.cpp
Labels: bug

#815 Gree: Support `YBOFB` models.
  SupportedProtocols.md
  src/IRac.cpp
  src/IRac.h
  src/ir_Gree.cpp
  src/ir_Gree.h
  src/ir_Kelvinator.h
  test/IRac_test.cpp
  test/ir_Gree_test.cpp
Labels: enhancement

#831 Fix some swing problems with the Mitsubishi HAVC protocol
  src/IRac.cpp
  src/IRac.h
  src/ir_Mitsubishi.cpp
  src/ir_Mitsubishi.h
  test/IRac_test.cpp
  test/ir_Mitsubishi_test.cpp
Labels: enhancement

#826 making some change on Daikin176bits to work with IRMQTTServer
  keywords.txt
  src/IRac.cpp
  src/IRsend.cpp
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  test/IRac_test.cpp
  test/ir_Daikin_test.cpp
Labels: enhancement

#823 Midea: Support native temp units of Celsius & SwingV.
  src/IRac.cpp
  src/IRac.h
  src/ir_Midea.cpp
  src/ir_Midea.h
  test/IRac_test.cpp
  test/ir_Midea_test.cpp
Labels: enhancement

#832 Daikin128: Full detailed support & common a/c support.
  src/IRac.cpp
  src/IRac.h
  src/IRutils.cpp
  src/IRutils.h
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  test/IRac_test.cpp
  test/IRutils_test.cpp
  test/ir_Daikin_test.cpp
Labels: enhancement

#833 v2.6.4 release
  README.md
  ReleaseNotes.md
  SupportedProtocols.md
  examples/IRMQTTServer/IRMQTTServer.h
  keywords.txt
  library.json
  library.properties
  src/IRremoteESP8266.h
Labels: enhancement

#836 Basic support for Amcor A/C protocol.
  SupportedProtocols.md
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRutils.cpp
  src/ir_Amcor.cpp
  test/Makefile
  test/ir_Amcor_test.cpp
  tools/Makefile
Labels: enhancement

#838 IRMQTTServer: Generate protocol and bit size html selects
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: enhancement
