Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2020-05, with the labels that each got.

#1095 Set correct return type for `.calibrate()`
  src/ir_Amcor.h
  src/ir_Argo.h
  src/ir_Coolix.h
  src/ir_Daikin.h
  src/ir_Electra.h
  src/ir_Fujitsu.h
  src/ir_Goodweather.h
  src/ir_Gree.h
  src/ir_Haier.h
  src/ir_Hitachi.h
  src/ir_Kelvinator.h
  src/ir_LG.h
  src/ir_Midea.h
  src/ir_Mitsubishi.h
  src/ir_MitsubishiHeavy.h
  src/ir_Neoclima.h
  src/ir_Panasonic.h
  src/ir_Samsung.h
  src/ir_Sharp.h
  src/ir_Tcl.h
  src/ir_Toshiba.h
  src/ir_Trotec.h
  src/ir_Vestel.h
  src/ir_Whirlpool.h
Labels: bug

#1102 Update auto_analyse to use new decode call structure.
  tools/auto_analyse_raw_data.py
  tools/auto_analyse_raw_data_test.py
Labels: enhancement

#1094 Improved support for SharpAc.
  keywords.txt
  src/IRac.cpp
  src/IRac.h
  src/ir_Sharp.cpp
  src/ir_Sharp.h
  test/IRac_test.cpp
  test/ir_Sharp_test.cpp
Labels: Pending Confirmation, enhancement

#1098 Add detailed support for Delonghi A/C
  SupportedProtocols.md
  src/IRac.cpp
  src/IRac.h
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/ir_Daikin.h
  src/ir_Delonghi.cpp
  src/ir_Delonghi.h
  src/locale/defaults.h
  test/IRac_test.cpp
  test/Makefile
  test/ir_Delonghi_test.cpp
  tools/Makefile
Labels: enhancement

#1099 IRMQTTServer: Better handle power & mode operations for Home Assistant.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  test/ir_Daikin_test.cpp
Labels: bug, enhancement

#1110 Use pattern rules in Makefiles to reduce specific rule
  test/Makefile
  tools/Makefile
Labels: enhancement

#1115 Add support for `Doshisha` LED light protocol
  SupportedProtocols.md
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/ir_Doshisha.cpp
  src/locale/defaults.h
  test/ir_Doshisha_test.cpp
Labels: enhancement

#1104 Add RawToPronto.py tool & improve `sendPronto()` precision
  src/ir_Pronto.cpp
  test/ir_Pronto_test.cpp
  tools/auto_analyse_raw_data.py
  tools/raw_to_pronto_code.py
  tools/raw_to_pronto_code_test.py
Labels: enhancement

#1106 Add support for Multibrackets protocol.
  SupportedProtocols.md
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/ir_Multibrackets.cpp
  src/locale/defaults.h
  test/ir_Multibrackets_test.cpp
Labels: enhancement

#1107 [BREAKING][BUG] Fix Symphony protocol.
  SupportedProtocols.md
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/ir_Symphony.cpp
  test/ir_Symphony_test.cpp
Labels: bug, enhancement

#1117 Use GMT/UTC for the timestamp.
  SupportedProtocols.md
  tools/scrape_supported_devices.py
Labels: enhancement

#1120 Gree: Add option to control display temp source.
  src/IRtext.cpp
  src/IRtext.h
  src/ir_Gree.cpp
  src/ir_Gree.h
  src/locale/defaults.h
  test/IRac_test.cpp
  test/ir_Gree_test.cpp
Labels: Pending Confirmation, enhancement

#1122 Improve `raw_to_pronto_code.py`
  test/ir_Pronto_test.cpp
  tools/raw_to_pronto_code.py
  tools/raw_to_pronto_code_test.py
Labels: enhancement

#1126 update auto_analyse script to use new param documentation
  tools/auto_analyse_raw_data.py
  tools/auto_analyse_raw_data_test.py
Labels: enhancement

#1124 Gree: Enable native support for Fahrenheit
  SupportedProtocols.md
  keywords.txt
  src/IRac.cpp
  src/IRac.h
  src/ir_Gree.cpp
  src/ir_Gree.h
  test/IRac_test.cpp
  test/ir_Gree_test.cpp
Labels: enhancement

#1125 Add basic support for Carrier 40 & 64 bit protocols.
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/ir_Carrier.cpp
  src/locale/defaults.h
  test/ir_Carrier_test.cpp
Labels: enhancement

#1132 v2.7.7 release
  README.md
  README_fr.md
  ReleaseNotes.md
  SupportedProtocols.md
  keywords.txt
  library.json
  library.properties
  src/IRremoteESP8266.h
  src/ir_Carrier.cpp
Labels: enhancement

#1133 CarrierAc64: Add detailed support.
  src/IRac.cpp
  src/IRac.h
  src/ir_Carrier.cpp
  src/ir_Carrier.h
  test/IRac_test.cpp
  test/ir_Carrier_test.cpp
Labels: enhancement

#1139 Add experimental support for Hitachi A/C 344 bit protocol
  src/IRrecv.cpp
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/IRutils.cpp
  src/ir_Hitachi.cpp
  src/ir_Hitachi.h
  src/locale/defaults.h
  test/ir_Hitachi_test.cpp
Labels: enhancement

#1140 scrape_supported_devices.py: avoid changes to SupportedProtocols.md
  tools/scrape_supported_devices.py
Labels: enhancement

#1143 Comments update + cleanup
  SupportedProtocols.md
  src/IRremoteESP8266.h
  src/IRsend.h
  src/IRutils.cpp
Labels: enhancement

#1144 Update D_STR_IRRECVDUMP_STARTUP text.
  examples/IRrecvDemo/IRrecvDemo.ino
  src/IRsend.cpp
  src/locale/de-CH.h
  src/locale/de-DE.h
  src/locale/defaults.h
  src/locale/es-ES.h
  src/locale/fr-FR.h
  src/locale/it-IT.h
  src/locale/zh-CN.h
  tools/auto_analyse_raw_data.py
Labels: enhancement

#1147 Hitachi344: Add detailed support and change bit ordering.
  src/IRac.cpp
  src/IRac.h
  src/IRrecv.cpp
  src/IRrecv.h
  src/ir_Hitachi.cpp
  src/ir_Hitachi.h
  test/IRac_test.cpp
  test/ir_Hitachi_test.cpp
Labels: enhancement

#1149 Minor code cleanups
  src/IRrecv.cpp
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/IRutils.cpp
  src/ir_Gree.cpp
  src/ir_Panasonic.cpp
  src/ir_Panasonic.h
Labels: enhancement

#1150 Add Doxygen automatic documentation config for the library.
  Doxyfile
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRutils.cpp
  src/IRutils.h
  src/ir_Carrier.cpp
  src/ir_Hitachi.cpp
  src/ir_Kelvinator.cpp
  src/ir_Kelvinator.h
Labels: enhancement

#1152 Add Corona AC Protocol
  src/IRac.cpp
  src/IRac.h
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/IRtext.h
  src/IRutils.cpp
  src/ir_Corona.cpp
  src/ir_Corona.h
  src/locale/defaults.h
  test/IRac_test.cpp
  test/ir_Corona_test.cpp
Labels: enhancement

#1148 Hitachi344: Add Swing(H) and improve Swing(V)
  src/IRac.cpp
  src/IRac.h
  src/ir_Hitachi.cpp
  src/ir_Hitachi.h
  src/ir_MitsubishiHeavy.cpp
  test/IRac_test.cpp
  test/ir_Hitachi_test.cpp
Labels: enhancement
