Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2020-07, with the labels that each got.

#1212 ToshibaAc: Rework to support Carrier models and add more settings.
  examples/TurnOnToshibaAC/TurnOnToshibaAC.ino
  src/IRac.cpp
  src/IRac.h
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.h
  src/IRutils.cpp
  src/IRutils.h
  src/ir_Toshiba.cpp
  src/ir_Toshiba.h
  test/IRac_test.cpp
  test/IRutils_test.cpp
  test/ir_Toshiba_test.cpp
Labels: Pending Confirmation, enhancement

#1213 Added modification to Midea unit to support Danby DAC AC units.
  src/IRac.cpp
  src/IRac.h
  src/IRtext.cpp
  src/IRtext.h
  src/ir_Midea.cpp
  src/ir_Midea.h
  src/locale/defaults.h
  test/IRac_test.cpp
  test/ir_Midea_test.cpp
Labels: enhancement

#1215 [Bug] Fix mistake in `IRLgAc::convertFan()`.
  src/ir_LG.cpp
  src/ir_LG.h
  test/ir_LG_test.cpp
Labels: bug, enhancement

#1218 Add Sanyo A/C (72 bit) protocol with detailed support.
  src/IRac.cpp
  src/IRac.h
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/IRutils.cpp
  src/ir_Sanyo.cpp
  src/ir_Sanyo.h
  src/locale/defaults.h
  test/IRac_test.cpp
  test/ir_Sanyo_test.cpp
Labels: enhancement

#1219 Consolidate common code: Inverted byte pairs
  src/ir_Hitachi.cpp
  src/ir_MitsubishiHeavy.cpp
Labels: enhancement

#1221 Samsung36: Adjust timings & update unit tests.
  src/ir_Samsung.cpp
  src/ir_Samsung.h
  test/ir_Samsung_test.cpp
Labels: Pending Confirmation, enhancement

#1222 Pioneer: Update timings based on user collected data.
  src/ir_Pioneer.cpp
  test/ir_Pioneer_test.cpp
Labels: enhancement
