Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2020-10, with the labels that each got.

#1287 Add some missing Doxygen class/data-type descriptions.
  src/ir_Airwell.h
  src/ir_Amcor.h
  src/ir_Argo.h
  src/ir_Carrier.h
  src/ir_Corona.h
  src/ir_Delonghi.h
  src/ir_Gree.h
  src/ir_Haier.h
  src/ir_Midea.h
  src/ir_Technibel.h
  src/ir_Transcold.h
  src/ir_Voltas.h
Labels: Documentation, Hacktoberfest

#1288 refactor ir_Daikin
  src/ir_Daikin.cpp
  src/ir_Daikin.h
Labels: Hacktoberfest, enhancement

#1290 refactor ir_Electra
  src/ir_Electra.cpp
  src/ir_Electra.h
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted

#1291 Add basic support for the Mirage Protocol.
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/IRutils.cpp
  src/ir_Mirage.cpp
  src/locale/defaults.h
  test/ir_Mirage_test.cpp
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted

#1292 IRrecvDumpV2+: Add tolerance setting.
  examples/IRrecvDumpV2/IRrecvDumpV2.ino
  examples/IRrecvDumpV3/IRrecvDumpV3.ino
  src/locale/defaults.h
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted

#1293 de-DE update for recent addition of 'tolerance'
  src/locale/de-DE.h
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted

#1294 Backfill missing de-DE strings
  src/locale/de-DE.h
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted

#1296 Translate docs/README.md to German
  docs/README_de.md
Labels: Documentation, Hacktoberfest, hacktoberfest-accepted

#1295 refactor ir_Goodweather
  src/ir_Goodweather.cpp
  src/ir_Goodweather.h
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted

#1301 Feature/fix typos
  src/IRac.cpp
  src/IRrecv.cpp
  src/IRutils.cpp
  src/ir_Airwell.cpp
  src/ir_Amcor.cpp
  src/ir_Argo.cpp
  src/ir_Argo.h
  src/ir_Carrier.cpp
  src/ir_Coolix.cpp
  src/ir_Daikin.cpp
  src/ir_Delonghi.cpp
  src/ir_Electra.cpp
  src/ir_Fujitsu.cpp
  src/ir_Goodweather.cpp
  src/ir_Gree.cpp
  src/ir_Haier.cpp
  src/ir_Hitachi.cpp
  src/ir_Kelvinator.cpp
  src/ir_LG.cpp
  src/ir_Midea.cpp
  src/ir_Mitsubishi.cpp
  src/ir_MitsubishiHeavy.cpp
  src/ir_Neoclima.cpp
  src/ir_Panasonic.cpp
  src/ir_Samsung.cpp
  src/ir_Sanyo.cpp
  src/ir_Sharp.cpp
  src/ir_Sherwood.cpp
  src/ir_Tcl.cpp
  src/ir_Technibel.cpp
  src/ir_Teco.cpp
  src/ir_Toshiba.cpp
  src/ir_Toshiba.h
  src/ir_Transcold.cpp
  src/ir_Trotec.cpp
  src/ir_Trotec.h
  src/ir_Vestel.cpp
  src/ir_Voltas.cpp
  src/ir_Whirlpool.cpp
  test/ir_Midea_test.cpp
Labels: Documentation, Hacktoberfest, hacktoberfest-accepted

#1303 Add pt-BR locale
  examples/IRrecvDumpV2/platformio.ini
  src/locale/pt-BR.h
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted

#1304 [Bug] Fix LG2 timings and refactor `decodeLG()`
  src/ir_LG.cpp
  test/ir_LG_test.cpp
Labels: Hacktoberfest, Pending Confirmation, bug, enhancement, hacktoberfest-accepted

#1308 refactor ir_Hitachi
  src/ir_Hitachi.cpp
  src/ir_Hitachi.h
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted

#1310 Add support for Elite Screens protocol.
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/ir_EliteScreens.cpp
  src/locale/defaults.h
  test/ir_EliteScreens_test.cpp
Labels: Hacktoberfest, Pending Confirmation, enhancement, hacktoberfest-accepted

#1314 [BUG] `defaultBits()` returned incorrect result for `PANASONIC_AC`
  src/IRsend.cpp
  test/ir_Panasonic_test.cpp
Labels: Hacktoberfest, bug, hacktoberfest-accepted
