Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2020-06, with the labels that each got.

#1154 Doxygen-ify IRac.cpp
  src/IRac.cpp
Labels: Documentation

#1155 Doxygen-ify the IRtimer files.
  src/IRtimer.cpp
  src/IRtimer.h
Labels: Documentation

#1156 Doxify more protocol files.
  src/ir_Airwell.cpp
  src/ir_Aiwa.cpp
  src/ir_Amcor.cpp
  src/ir_Amcor.h
  src/ir_Argo.cpp
  src/ir_Argo.h
Labels: Documentation

#1158 Doxygen-ify the protocols beginning with 'C'
  src/ir_Carrier.cpp
  src/ir_Carrier.h
  src/ir_Coolix.cpp
  src/ir_Coolix.h
  src/ir_Corona.cpp
  src/ir_Corona.h
Labels: Documentation

#1160 Remove legacy "compatible with" sections
  src/ir_Amcor.cpp
  src/ir_Carrier.cpp
  src/ir_Carrier.h
  src/ir_Coolix.cpp
  src/ir_Coolix.h
  src/ir_Fujitsu.cpp
  src/ir_Fujitsu.h
  src/ir_Goodweather.cpp
  src/ir_Gree.cpp
  src/ir_Hitachi.cpp
  src/ir_LG.cpp
  src/ir_Midea.cpp
  src/ir_Mitsubishi.cpp
  src/ir_Mitsubishi.h
  src/ir_Neoclima.cpp
  src/ir_Neoclima.h
  src/ir_Sharp.cpp
  src/ir_Sharp.h
  src/ir_Toshiba.cpp
  src/ir_Vestel.cpp
  src/ir_Whirlpool.cpp
Labels: Documentation

#1161 Add a `doxygen` check to CI/Travis.
  .travis.yml
  src/ir_Mitsubishi.cpp
  src/ir_NEC.cpp
  src/locale/README.md
Labels: Documentation, enhancement

#1159 scrape_supported_devices warn about misplaced or legacy supports sections
  tools/scrape_supported_devices.py
Labels: Documentation, enhancement

#1163 Add Supports sections to some files
  src/ir_Denon.cpp
  src/ir_GICable.cpp
  src/ir_Lutron.cpp
  src/ir_Magiquest.h
  src/ir_Nikai.cpp
  src/ir_Pioneer.cpp
  src/ir_Pronto.cpp
  src/ir_RC5_RC6.cpp
  src/ir_Sanyo.cpp
Labels: Documentation, enhancement

#1164 Update auto_analyse_raw_data.py with better code comment sections
  tools/auto_analyse_raw_data.py
  tools/auto_analyse_raw_data_test.py
Labels: Documentation, enhancement

#1165 Doxygen-ate all the protocols beginning with `D`
  src/ir_Argo.cpp
  src/ir_Carrier.cpp
  src/ir_Corona.cpp
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  src/ir_Delonghi.cpp
  src/ir_Delonghi.h
  src/ir_Denon.cpp
  src/ir_Dish.cpp
  src/ir_Doshisha.cpp
Labels: Documentation

#1166 Add Supports sections to more files
  src/ir_GlobalCache.cpp
  src/ir_JVC.cpp
  src/ir_Lasertag.cpp
  src/ir_MWM.cpp
  src/ir_Trotec.h
Labels: Documentation, enhancement

#1167 EF'ing more doxygenation
  src/ir_Electra.cpp
  src/ir_Electra.h
  src/ir_Epson.cpp
  src/ir_Fujitsu.cpp
  src/ir_Fujitsu.h
Labels: Documentation, enhancement

#1169 G'eee! More doxygen updates.
  src/ir_GICable.cpp
  src/ir_GlobalCache.cpp
  src/ir_Goodweather.cpp
  src/ir_Goodweather.h
  src/ir_Gree.cpp
  src/ir_Gree.h
Labels: Documentation

#1171 Add experimental support for Midea's NEC-like protocol.
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/ir_Midea.cpp
  src/ir_Midea.h
  src/ir_NEC.cpp
  src/locale/defaults.h
  test/ir_Midea_test.cpp
Labels: enhancement

#1174 Treat compiler warnings as errors.
  examples/CommonAcControl/platformio.ini
  examples/IRrecvDumpV2/platformio.ini
  examples/SmartIRRepeater/SmartIRRepeater.ino
  examples/SmartIRRepeater/platformio.ini
  src/IRac.cpp
  src/IRsend.cpp
  test/Makefile
Labels: enhancement

#1175 Remove `calcLGChecksum()` and use new generic `sumNibbles()`
  src/IRutils.cpp
  src/IRutils.h
  src/ir_LG.cpp
  test/IRutils_test.cpp
  test/ir_LG_test.cpp
Labels: enhancement

#1177 Add Duux remote & A/C to supported devices.
  src/ir_NEC.h
  src/ir_Trotec.h
Labels: Documentation

#1179 Suppress more potential compiler warnings.
  src/IRac.cpp
Labels: enhancement

#1180 H'ow many more protocols are left to doxy?
  src/ir_Haier.cpp
  src/ir_Haier.h
  src/ir_Hitachi.cpp
  src/ir_Hitachi.h
Labels: Documentation

#1183 Load balance travis tasks to reduce wall clock time.
  .travis.yml
Labels: enhancement

#1184 I Just Keep Loving doxygening protocols.
  src/ir_Inax.cpp
  src/ir_JVC.cpp
  src/ir_Kelvinator.cpp
  src/ir_Kelvinator.h
  src/ir_LG.cpp
  src/ir_LG.h
  src/ir_Lasertag.cpp
  src/ir_Lego.cpp
  src/ir_Lutron.cpp
Labels: Documentation

#1188 Set PlatformIO's default baudrate to 115200
  examples/BlynkIrRemote/platformio.ini
  examples/CommonAcControl/platformio.ini
  examples/ControlSamsungAC/platformio.ini
  examples/DumbIRRepeater/platformio.ini
  examples/IRGCSendDemo/platformio.ini
  examples/IRGCTCPServer/platformio.ini
  examples/IRMQTTServer/platformio.ini
  examples/IRServer/platformio.ini
  examples/IRrecvDemo/platformio.ini
  examples/IRrecvDump/platformio.ini
  examples/IRrecvDumpV2/platformio.ini
  examples/IRrecvDumpV3/platformio.ini
  examples/IRsendDemo/platformio.ini
  examples/IRsendProntoDemo/platformio.ini
  examples/JVCPanasonicSendDemo/platformio.ini
  examples/LGACSend/platformio.ini
  examples/SmartIRRepeater/platformio.ini
  examples/TurnOnArgoAC/platformio.ini
  examples/TurnOnDaikinAC/platformio.ini
  examples/TurnOnFujitsuAC/platformio.ini
  examples/TurnOnGreeAC/platformio.ini
  examples/TurnOnKelvinatorAC/platformio.ini
  examples/TurnOnMitsubishiAC/platformio.ini
  examples/TurnOnMitsubishiHeavyAc/platformio.ini
  examples/TurnOnPanasonicAC/platformio.ini
  examples/TurnOnToshibaAC/platformio.ini
  examples/TurnOnTrotecAC/platformio.ini
  examples/Web-AC-control/platformio.ini
  platformio.ini
Labels: enhancement

#1189 MMmmmmm, More Making Marvellous Method Manuals
  src/IRsend.h
  src/ir_Daikin.cpp
  src/ir_Hitachi.cpp
  src/ir_MWM.cpp
  src/ir_Magiquest.cpp
  src/ir_Magiquest.h
  src/ir_Midea.cpp
  src/ir_Midea.h
  src/ir_Mitsubishi.cpp
  src/ir_Mitsubishi.h
  src/ir_MitsubishiHeavy.cpp
  src/ir_MitsubishiHeavy.h
  src/ir_Multibrackets.cpp
Labels: Documentation, enhancement

#1191 Needlessly Procedural Repetitious Doxification
  src/IRrecv.h
  src/IRsend.h
  src/ir_Mitsubishi.cpp
  src/ir_NEC.cpp
  src/ir_NEC.h
  src/ir_Neoclima.cpp
  src/ir_Neoclima.h
  src/ir_Nikai.cpp
  src/ir_Panasonic.cpp
  src/ir_Panasonic.h
  src/ir_Pioneer.cpp
  src/ir_Pronto.cpp
  src/ir_RC5_RC6.cpp
  src/ir_RCMM.cpp
Labels: Documentation

#1193 [BUG] Carrier40: Use correct gap value.
  src/ir_Carrier.cpp
  test/ir_Carrier_test.cpp
Labels: bug

#1194 SsssSufferin’ ssssuccotash! Doxygen'ed again!
  src/IRsend.h
  src/ir_Neoclima.cpp
  src/ir_Samsung.cpp
  src/ir_Samsung.h
  src/ir_Sanyo.cpp
  src/ir_Sharp.cpp
  src/ir_Sharp.h
  src/ir_Sherwood.cpp
  src/ir_Sony.cpp
  src/ir_Symphony.cpp
Labels: Documentation, enhancement

#1195 Total Vexation With Doxygen!
  src/IRsend.h
  src/ir_Samsung.cpp
  src/ir_Tcl.cpp
  src/ir_Tcl.h
  src/ir_Teco.cpp
  src/ir_Teco.h
  src/ir_Toshiba.cpp
  src/ir_Toshiba.h
  src/ir_Trotec.cpp
  src/ir_Trotec.h
  src/ir_Vestel.cpp
  src/ir_Vestel.h
  src/ir_Whirlpool.cpp
  src/ir_Whirlpool.h
  src/ir_Whynter.cpp
Labels: Documentation, enhancement

#1196 Enable more Doxygen warnings
  Doxyfile
  src/IRac.cpp
  src/IRrecv.cpp
  src/IRsend.cpp
  src/ir_Amcor.cpp
  src/ir_Argo.cpp
  src/ir_Carrier.cpp
  src/ir_Coolix.cpp
  src/ir_Corona.cpp
  src/ir_Daikin.cpp
  src/ir_Delonghi.cpp
  src/ir_Electra.cpp
  src/ir_Fujitsu.cpp
  src/ir_Goodweather.cpp
  src/ir_Gree.cpp
  src/ir_Haier.cpp
  src/ir_Hitachi.cpp
  src/ir_Kelvinator.cpp
  src/ir_LG.cpp
  src/ir_Midea.cpp
  src/ir_Mitsubishi.cpp
  src/ir_MitsubishiHeavy.cpp
  src/ir_Neoclima.cpp
  src/ir_Panasonic.cpp
  src/ir_Samsung.cpp
  src/ir_Sharp.cpp
  src/ir_Tcl.cpp
  src/ir_Teco.cpp
  src/ir_Toshiba.cpp
  src/ir_Trotec.cpp
  src/ir_Vestel.cpp
  src/ir_Whirlpool.cpp
Labels: Documentation

#1197 Misc doxygen fixes.
  src/IRac.cpp
  src/IRac.h
  src/IRtext.cpp
  src/ir_Amcor.h
  src/ir_Argo.h
  src/ir_Carrier.h
  src/ir_Coolix.h
  src/ir_Corona.h
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  src/ir_Delonghi.h
  src/ir_Electra.h
  src/ir_Fujitsu.h
  src/ir_Goodweather.h
  src/ir_Gree.h
  src/ir_Haier.h
  src/ir_Hitachi.h
  src/ir_Kelvinator.h
  src/ir_LG.h
  src/ir_Midea.h
  src/ir_Mitsubishi.h
  src/ir_MitsubishiHeavy.cpp
  src/ir_MitsubishiHeavy.h
  src/ir_Neoclima.h
  src/ir_Panasonic.h
  src/ir_Samsung.h
  src/ir_Sharp.cpp
  src/ir_Sharp.h
  src/ir_Tcl.h
  src/ir_Teco.h
  src/ir_Toshiba.h
  src/ir_Trotec.h
  src/ir_Vestel.h
  src/ir_Whirlpool.h
Labels: Documentation

#1198 Add an overview/intro for the Library API
  Doxyfile
  docs/doxygen_index.md
Labels: Documentation

#1200 [BREAKING BUG] Fix Manchester code handling; Increase Airwell to `34` bits.
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/ir_Airwell.cpp
  test/IRrecv_test.cpp
  test/IRsend_test.cpp
  test/ir_Airwell_test.cpp
Labels: bug, enhancement

#1203 Update missing/incorrect doxygen comments
  src/IRac.h
  src/IRtimer.cpp
  src/IRtimer.h
  src/ir_Daikin.h
  src/ir_Mitsubishi.h
Labels: Documentation

#1204 Add detailed support for Airwell A/C protocol.
  src/IRac.cpp
  src/IRac.h
  src/ir_Airwell.cpp
  src/ir_Airwell.h
  test/IRac_test.cpp
  test/ir_Airwell_test.cpp
Labels: enhancement

#1207 Remove duplicate code from `IRToshibaAC::calcChecksum()`
  src/ir_Toshiba.cpp
Labels: enhancement
