Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2020-11, with the labels that each got.

#1316 Add basic support for Panasonic A/C 32bit/16bit protocol.
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/ir_Panasonic.cpp
  src/ir_Panasonic.h
  src/locale/defaults.h
  test/ir_Panasonic_test.cpp
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted

#1317 refactor ir_Kelvinator
  src/ir_Kelvinator.cpp
  src/ir_Kelvinator.h
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted

#1322 Update Kaysun supported models.
  src/ir_Coolix.h
  src/ir_Midea.h
  test/ir_Midea_test.cpp
Labels: Documentation

#1325 refactor ir_LG
  src/ir_LG.cpp
  src/ir_LG.h
Labels: enhancement

#1326 Fix a code comment.
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: Documentation

#1313 SharpAc: Add model support for A705
  src/IRac.cpp
  src/IRac.h
  src/IRsend.h
  src/IRutils.cpp
  src/ir_Sharp.cpp
  src/ir_Sharp.h
  test/IRac_test.cpp
  test/ir_Sharp_test.cpp
Labels: Hacktoberfest, enhancement, hacktoberfest-accepted

#1327 Midea: Add support for "Follow Me"/Sensor, Turbo, Light, & Timers
  src/IRac.cpp
  src/IRac.h
  src/IRtext.cpp
  src/IRtext.h
  src/ir_Coolix.h
  src/ir_Midea.cpp
  src/ir_Midea.h
  src/locale/defaults.h
  test/IRac_test.cpp
  test/ir_Midea_test.cpp
Labels: enhancement

#1332 [BUG] Typo preventing RC6 from compiling when other protocols disabled.
  src/IRrecv.h
Labels: bug

#1333 refactor ir_MitsubishiHeavy
  src/ir_MitsubishiHeavy.cpp
  src/ir_MitsubishiHeavy.h
Labels: enhancement

#1336 refactor ir_Mitsubishi
  src/ir_Mitsubishi.cpp
  src/ir_Mitsubishi.h
Labels: enhancement

#1337 [bug] Mitsubishi112 & 136: setSwingV incorrectly sets mode.
  src/ir_Mitsubishi.cpp
  test/ir_Mitsubishi_test.cpp
Labels: bug

#1340 Coolix: Improve Sensor(ZoneFollow) and add Vane Step support.
  src/ir_Coolix.cpp
  src/ir_Coolix.h
  test/ir_Coolix_test.cpp
Labels: enhancement

#1341 [Bug] Fix crash when IRac::sendAc(state_t, *state_t) called with SAMSUNG_AC & NULL
  src/IRac.cpp
  test/IRac_test.cpp
Labels: bug

#1346 Kelvinator: Update supported models.
  src/ir_Kelvinator.h
Labels: Documentation

#1344 Midea: Update supported devices & add notes for an odd Pioneer System.
  src/ir_Midea.h
  test/ir_Midea_test.cpp
Labels: Documentation, enhancement

#1345 Fujitsu: Handle toggles of Econo & Turbo better when the `IRac` interface is used.
  src/IRac.cpp
Labels: enhancement
