Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2020-08, with the labels that each got.

#1232 Add low level bit formating sanity checks.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
  examples/IRrecvDumpV2/IRrecvDumpV2.ino
  examples/IRrecvDumpV3/IRrecvDumpV3.ino
  src/IRutils.cpp
  src/IRutils.h
  test/IRutils_test.cpp
Labels: enhancement

#1210 rewrite ir_Gree
  src/ir_Gree.cpp
  src/ir_Gree.h
Labels: enhancement

#1235 [Breaking] Daikin176: Change operating mode values.
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  test/IRac_test.cpp
  test/ir_Daikin_test.cpp
Labels: Pending Confirmation, enhancement

#1226 move SPIFFS to LittleFS for ESP8266
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
  examples/Web-AC-control/Web-AC-control.h
  examples/Web-AC-control/Web-AC-control.ino
  examples/Web-AC-control/data/favicon.ico
  examples/Web-AC-control/data/level_1_off.svg
  examples/Web-AC-control/data/level_1_on.svg
  examples/Web-AC-control/data/level_2_off.svg
  examples/Web-AC-control/data/level_2_on.svg
  examples/Web-AC-control/data/level_3_off.svg
  examples/Web-AC-control/data/level_3_on.svg
  examples/Web-AC-control/data/level_4_off.svg
  examples/Web-AC-control/data/level_4_on.svg
  examples/Web-AC-control/data/ui.html
  examples/Web-AC-control/data/ui.js
  examples/Web-AC-control/platformio.ini
Labels: enhancement

#1243 Basic support for Voltas A/C protocol
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/IRutils.cpp
  src/ir_Voltas.cpp
  src/locale/defaults.h
  test/ir_Voltas_test.cpp
Labels: enhancement

#1245 [Bug] Incorrect usage of `assert()`
  examples/IRrecvDumpV2/IRrecvDumpV2.ino
  examples/IRrecvDumpV3/IRrecvDumpV3.ino
Labels: bug

#1240 rewrite ir_Gree & ir_Midea by using bit field
  src/ir_Gree.cpp
  src/ir_Gree.h
  src/ir_Midea.cpp
  src/ir_Midea.h
Labels: enhancement

#1247 rewrite Haier HSU07-HEA03
  src/ir_Haier.cpp
  src/ir_Haier.h
  test/ir_Haier_test.cpp
Labels: bug, enhancement

#1251 [BUG] TOSHIBA_AC: not turning off when using `IRac` class.
  src/IRac.cpp
  test/IRac_test.cpp
Labels: bug

#1248 Voltas: Add detailed support for Voltas A/Cs
  src/IRac.cpp
  src/IRac.h
  src/IRsend.h
  src/IRutils.cpp
  src/ir_Voltas.cpp
  src/ir_Voltas.h
  test/IRac_test.cpp
  test/ir_Voltas_test.cpp
Labels: enhancement

#1253 rewrite Haier YRW02 by using bit field
  src/ir_Haier.cpp
  src/ir_Haier.h
Labels: enhancement
