Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2020-09, with the labels that each got.

#1258 Add basic support for Transcold protocol.
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/ir_Transcold.cpp
  src/locale/defaults.h
  test/ir_Transcold_test.cpp
Labels: Pending Confirmation, enhancement

#1263 rewrite ir_Amcor by using bit field
  src/ir_Amcor.cpp
  src/ir_Amcor.h
Labels: enhancement

#1259 Technibel support
  src/IRac.cpp
  src/IRac.h
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/ir_Technibel.cpp
  src/ir_Technibel.h
  src/locale/defaults.h
  test/ir_Technibel_test.cpp
Labels: enhancement

#1264 rewrite ir_Argo by using bit field
  src/ir_Argo.cpp
  src/ir_Argo.h
Labels: enhancement

#1266 Technibel: Cleanup and code fixes/improvements.
  src/IRac.cpp
  src/IRac.h
  src/ir_Technibel.cpp
  src/ir_Technibel.h
  test/IRac_test.cpp
  test/ir_Technibel_test.cpp
Labels: Documentation, bug, enhancement

#1265 Neoclima: Add Economy & Fahrenheit support
  src/IRac.cpp
  src/IRac.h
  src/IRtext.cpp
  src/IRtext.h
  src/ir_Neoclima.cpp
  src/ir_Neoclima.h
  src/locale/defaults.h
  test/IRac_test.cpp
  test/ir_Neoclima_test.cpp
Labels: Pending Confirmation, enhancement

#1262 Fujitsu: Add support for timers.
  src/IRac.cpp
  src/IRac.h
  src/ir_Fujitsu.cpp
  src/ir_Fujitsu.h
  test/IRac_test.cpp
  test/ir_Fujitsu_test.cpp
Labels: enhancement

#1269 rewrite ir_Carrier by using bit field
  src/ir_Carrier.cpp
  src/ir_Carrier.h
  test/ir_Carrier_test.cpp
Labels: enhancement

#1270 Add Zhongxian Li to Contributers.md
  .github/Contributors.md
Labels: Documentation

#1271 IRMQTTServer: Change how MQTT packet/buffer size is set.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
  examples/IRMQTTServer/platformio.ini
Labels: enhancement

#1272 tools/mkkeywords: Fix minor parsing issue.
  tools/mkkeywords
Labels: Documentation, enhancement

#1274 rewrite ir_Corona
  src/ir_Corona.cpp
  src/ir_Corona.h
  test/ir_Corona_test.cpp
Labels: enhancement

#1276 Airwell/Whirlpool: Add handling of previous state to `.toCommon()`
  src/IRac.cpp
  src/ir_Airwell.cpp
  src/ir_Airwell.h
  src/ir_Whirlpool.cpp
  src/ir_Whirlpool.h
Labels: enhancement

#1281 Add question & note about VS1838b use to issue template.
  .github/issue_template.md
Labels: Documentation

#1280 SamsungAC: Unit tests to help debug poor signal
  test/ir_Samsung_test.cpp
Labels: enhancement, wontfix

#1278 Transcold: Add detailed support.
  src/IRac.cpp
  src/IRac.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/ir_Transcold.cpp
  src/ir_Transcold.h
  test/IRac_test.cpp
  test/ir_Transcold_test.cpp
Labels: enhancement

#1284 Whirlpool: Change default mode in `convertMode()`
  src/ir_Whirlpool.cpp
  src/ir_Whirlpool.h
  test/IRac_test.cpp
  test/ir_Whirlpool_test.cpp
Labels: enhancement

#1285 refactor ir_Delonghi
  src/ir_Delonghi.cpp
  src/ir_Delonghi.h
Labels: enhancement
