Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2020-12, with the labels that each got.

#1351 [BUG] Workaround for ESP32 hw timer library calls not in IRAM.
  src/IRrecv.cpp
Labels: ESP32, bug

#1352 Move global vars in IRrecv into a namespace.
  src/IRrecv.cpp
Labels: enhancement

#1354 [Bug] IRMQTTServer: Compiler error under PlatformIO on Windows.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: bug

#1348 Update issue templates
  .github/ISSUE_TEMPLATE/problem-report.md
Labels: Documentation

#1355 Delete issue_template.md
  .github/issue_template.md
Labels: Documentation

#1349 refactor ir_Neoclima
  src/ir_Neoclima.cpp
  src/ir_Neoclima.h
Labels: enhancement

#1358 refactor ir_Samsung
  src/ir_Samsung.cpp
  src/ir_Samsung.h
Labels: enhancement

#1362 Lasertag: Increase matching tolerance.
  src/ir_Lasertag.cpp
Labels: enhancement

#1363 Gree: List Amana as supported.
  src/ir_Gree.h
Labels: Documentation

#1359 Fix Sensor Location error & refactor ir_Sanyo
  src/ir_Sanyo.cpp
  src/ir_Sanyo.h
  test/IRac_test.cpp
  test/ir_Sanyo_test.cpp
Labels: bug, enhancement
