Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2020-02, with the labels that each got.

#1037 Coolix: Subtle protocol timing adjustments
  src/ir_Coolix.cpp
  test/IRac_test.cpp
  test/ir_Coolix_test.cpp
Labels: Pending Confirmation, enhancement

#1041 [Bug] Coolix: `setRaw()` doesn't update power state.
  src/ir_Coolix.cpp
  test/ir_Coolix_test.cpp
Labels: bug

#1038 IRMQTTServer: Fix bug when receiving an A/C message and not re-transmitting it.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
  examples/IRrecvDumpV2/IRrecvDumpV2.ino
  src/IRac.cpp
  src/IRac.h
  src/ir_Midea.cpp
  src/ir_Sanyo.cpp
  test/IRac_test.cpp
  test/ir_Daikin_test.cpp
Labels: bug

#1043 gc_decode: Add repeat support for pronto codes.
  test/ir_Pronto_test.cpp
  tools/gc_decode.cpp
Labels: enhancement

#1047 Italian locale
  src/locale/it-IT.h
Labels: enhancement

#1048 Samsung AC Display and VirusDoctor toggles
  src/ir_Samsung.cpp
  src/ir_Samsung.h
Labels: enhancement

#1049 SamsungAc: Add full support for light & ion.
  src/IRac.cpp
  src/IRac.h
  src/ir_Samsung.cpp
  test/IRac_test.cpp
  test/ir_Samsung_test.cpp
Labels: enhancement

#1051 Electra: Add improved feature support.
  src/IRac.cpp
  src/IRac.h
  src/ir_Electra.cpp
  src/ir_Electra.h
  test/IRac_test.cpp
  test/ir_Electra_test.cpp
Labels: enhancement

#1054 v2.7.4 release
  README.md
  README_fr.md
  ReleaseNotes.md
  SupportedProtocols.md
  keywords.txt
  library.json
  library.properties
  src/IRremoteESP8266.h
Labels: enhancement

#1055 Improve Home-Assistant discovery by sending a 'device' with the discovery packet
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: enhancement
