Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2021-12, with the labels that each got.

#1696 ESP32-C3: Work around for some C3 specific compiler issues.
  src/IRrecv.cpp
Labels: enhancement, ESP32

#1698 TCL: Update supported devices.
  src/ir_Tcl.h
Labels: Documentation

#1697 Add basic support for COOLIX48 protocol.
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/ir_Coolix.cpp
  src/ir_Coolix.h
  src/locale/defaults.h
  test/ir_Coolix_test.cpp
Labels: enhancement

#1700 Reduce build warnings
  src/ir_Kelon.cpp
Labels: enhancement, Documentation

#1702 Fujitsu: Update supported A/C models
  src/ir_Fujitsu.h
Labels: Documentation

#1705 Better fix for #1699
  src/IRsend.h
  src/ir_Kelon.cpp
Labels: enhancement

#1708 Add tool to convert protocol & code to raw timing info.
  .gitignore
  tools/Makefile
  tools/code_to_raw.cpp
  tools/code_to_raw_test.sh
Labels: enhancement

#1709 Reduce time for workflow/Build
  .github/workflows/Build.yml
Labels: enhancement

#1712 Workflows Split UnitTests Tools to separate job
  .github/workflows/UnitTests.yml
Labels: enhancement

#1714 Fix old Sony CD-Player Remote (12 Bit)
  src/ir_Sony.cpp
Labels: bug

#1717 Add a structured library version number.
  .github/workflows/MetaChecks.yml
  examples/IRMQTTServer/IRMQTTServer.ino
  examples/IRrecvDumpV2/IRrecvDumpV2.ino
  examples/IRrecvDumpV3/IRrecvDumpV3.ino
  src/IRremoteESP8266.h
  tools/extract_lib_version.sh
Labels: enhancement, Documentation

#1715 [BUG] Arduino ESP32 Core v2.0.2+ crashes due to our timer hack.
  src/IRrecv.cpp
Labels: bug, enhancement, ESP32
