Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2021-07, with the labels that each got.

#1494 Add support for Kelon ACs
  .github/Contributors.md
  src/IRac.cpp
  src/IRac.h
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/IRutils.cpp
  src/IRutils.h
  src/ir_Kelon.cpp
  src/ir_Kelon.h
  src/locale/defaults.h
  test/ir_Kelon_test.cpp
Labels: enhancement

#1515 Panasonic AC - Fix Low and High fan speed
  src/ir_Panasonic.cpp
  src/ir_Panasonic.h
  test/IRac_test.cpp
  test/ir_Panasonic_test.cpp
Labels: enhancement

#1517 [BUG] Illegal Heap write in rawbuf when the capture has overflowed.
  src/IRrecv.cpp
  src/IRrecv.h
  test/IRrecv_test.cpp
Labels: bug

#1527 Add Mitsubishi AC "fan only" mode
  src/ir_Mitsubishi.cpp
  src/ir_Mitsubishi.h
Labels: enhancement

#1530 [LG2] Add fan speed, Swing, & Light support for new `AKB74955603` model
  src/IRac.cpp
  src/IRac.h
  src/IRsend.h
  src/IRutils.cpp
  src/ir_LG.cpp
  src/ir_LG.h
  test/IRac_test.cpp
  test/ir_LG_test.cpp
Labels: enhancement

#1532 Refactor `decodeMitsubishiAC()`
  src/ir_Mitsubishi.cpp
  test/ir_Mitsubishi_test.cpp
Labels: enhancement

#1529 TCL112AC: Add support for quiet/mute setting.
  src/IRac.cpp
  src/IRac.h
  src/ir_Tcl.cpp
  src/ir_Tcl.h
  test/IRac_test.cpp
  test/ir_Tcl_test.cpp
Labels: Pending Confirmation, enhancement

#1536 Reduce memory fragementation cause by String.
  src/IRutils.cpp
Labels: enhancement

#1540 Daikin2: Add support for Humidity setting/operation.
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  test/IRac_test.cpp
  test/ir_Daikin_test.cpp
Labels: enhancement

#1541 IRMQTTServer: Build a minimal OTA image via PlatformIO.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/platformio.ini
  src/IRrecv.h
Labels: enhancement
