Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2021-08, with the labels that each got.

#1544 Daikin176: Add support for Unit Id.
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  test/IRac_test.cpp
  test/ir_Daikin_test.cpp
Labels: enhancement

#1545 [LG] Add support for `AKB73757604` model
  src/IRac.cpp
  src/IRac.h
  src/IRsend.h
  src/IRtext.cpp
  src/IRtext.h
  src/IRutils.cpp
  src/ir_LG.cpp
  src/ir_LG.h
  src/locale/defaults.h
  test/IRac_test.cpp
  test/ir_LG_test.cpp
Labels: Pending Confirmation, enhancement

#1551 [Bug] Make `strToSwingH()` match "Right Max"
  src/IRac.cpp
Labels: bug

#1554 SamsungAc: Redo/fix checksum calculations.
  src/ir_Samsung.cpp
  src/ir_Samsung.h
  test/ir_Samsung_test.cpp
Labels: enhancement

#1562 SamsungAc: Use `sendExtended()` going forward.
  src/ir_Samsung.cpp
  test/IRac_test.cpp
  test/ir_Samsung_test.cpp
Labels: enhancement

#1567 DAIKIN216: Update supported models.
  src/ir_Daikin.h
Labels: Documentation

#1566 Add support for new `TROTEC_3550` A/C protocol
  src/IRac.cpp
  src/IRac.h
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/IRutils.cpp
  src/ir_Trotec.cpp
  src/ir_Trotec.h
  src/locale/defaults.h
  test/IRac_test.cpp
  test/ir_Trotec_test.cpp
Labels: enhancement

#1568 Detailed support for Tornado/Sanyo 88-bit A/C protocol
  src/IRac.cpp
  src/IRac.h
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/IRutils.cpp
  src/ir_Sanyo.cpp
  src/ir_Sanyo.h
  src/locale/defaults.h
  test/IRac_test.cpp
  test/ir_Sanyo_test.cpp
Labels: enhancement

#1570 Fix pylint issues due to pylint update.
  tools/auto_analyse_raw_data.py
  tools/scrape_supported_devices.py
Labels: enhancement

#1581 Updating Support information
  src/ir_Midea.h
Labels: Documentation

#1580 PROTECT PAC 3900X
  src/ir_Trotec.h
Labels: Documentation

#1585 Fix doxygen error
  src/ir_Trotec.h
Labels: Documentation

#1583 Change when some github workflows run
  .github/workflows/Documentation.yml
  .github/workflows/Lint.yml
  .github/workflows/UnitTests.yml
Labels: enhancement

#1591 SharpAc: Update supported models
  src/ir_Sharp.h
Labels: Documentation
