Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2021-06, with the labels that each got.

#1491 Fix compiler warnings causing Travis failures.
  examples/IRrecvDumpV2/platformio.ini
  examples/SmartIRRepeater/platformio.ini
  src/IRac.cpp
  src/IRrecv.cpp
Labels: enhancement

#1489 Update supported model info
  src/ir_Electra.h
Labels: Documentation

#1490 Fix undefined constant
  src/ir_Fujitsu.h
Labels: enhancement

#1492 Daikin64: Add support for Heat mode
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  test/ir_Daikin_test.cpp
Labels: enhancement

#1500 IRac: Fix off-by-one error in Coolix's sleep.
  src/IRac.cpp
Labels: bug

#1499 Fix MDNS in IRServer and IRMQTTServer
  examples/IRMQTTServer/IRMQTTServer.ino
  examples/IRServer/IRServer.ino
Labels: Pending Confirmation, enhancement

#1502 IRac: Change Coolix to send special messages after a normal message.
  src/IRac.cpp
  test/IRac_test.cpp
Labels: enhancement

#1504 Experimental basic support for Teknopoint A/C protocol
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/IRutils.cpp
  src/ir_Teknopoint.cpp
  src/locale/defaults.h
  test/ir_Teknopoint_test.cpp
Labels: enhancement

#1509 [GREE] Update inter-message gap timing
  src/ir_Gree.cpp
  src/ir_Gree.h
  test/ir_Gree_test.cpp
Labels: enhancement
