Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2021-11, with the labels that each got.

#1661 [IRrecvDumpV2/3] Add platformIO build envs for Russian & Swedish
  examples/IRrecvDumpV2/platformio.ini
  examples/IRrecvDumpV3/platformio.ini
Labels: enhancement, Documentation

#1659 [HAIER_AC176/HAIER_AC_YRW02] Add support degree Fahrenheit
  src/IRac.cpp
  src/IRac.h
  src/ir_Haier.cpp
  src/ir_Haier.h
  test/IRac_test.cpp
  test/ir_Haier_test.cpp
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted

#1662 [SamsungAc] Add support for On, Off, & Sleep Timers
  src/IRac.cpp
  src/IRac.h
  src/ir_Samsung.cpp
  src/ir_Samsung.h
  test/IRac_test.cpp
  test/ir_Samsung_test.cpp
Labels: enhancement

#1663 Fix `IRHaierAC176::getTemp()` return value description
  src/ir_Haier.cpp
Labels: Documentation

#1660 [MIRAGE] Experimental detailed support for KKG29A-C1 remote.
  src/IRac.cpp
  src/IRac.h
  src/IRsend.h
  src/IRtext.cpp
  src/IRtext.h
  src/IRutils.cpp
  src/ir_Mirage.cpp
  src/ir_Mirage.h
  src/locale/defaults.h
  test/IRac_test.cpp
  test/ir_Mirage_test.cpp
Labels: enhancement, Pending Confirmation

#1653 [Gree] Add `SwingH` & `Econo` control.
  src/IRac.cpp
  src/IRac.h
  src/ir_Gree.cpp
  src/ir_Gree.h
  test/IRac_test.cpp
  test/ir_Gree_test.cpp
Labels: enhancement, Hacktoberfest, Pending Confirmation, hacktoberfest-accepted

#1667 SamsungAc: Add support for Horizontal Swing & Econo
  src/IRac.cpp
  src/IRac.h
  src/ir_Samsung.cpp
  src/ir_Samsung.h
  test/IRac_test.cpp
  test/ir_Samsung_test.cpp
Labels: enhancement

#1673 [HAIER_AC176] Update supported remotes
  src/ir_Haier.h
Labels: Documentation

#1671 SamsungAc: Change `beep` setting to a toggle.
  src/IRac.cpp
  src/ir_Samsung.cpp
  src/ir_Samsung.h
  test/IRac_test.cpp
  test/ir_Samsung_test.cpp
Labels: enhancement, Pending Confirmation

#1674 [HAIER_AC176/HAIER_AC_YRW02] Small fix `Quiet` and `Turbo` test
  test/ir_Haier_test.cpp
Labels: enhancement

#1678 [SAMSUNG_AC] Highest fan speed is available without Powerful setting.
  src/ir_Samsung.cpp
  test/ir_Samsung_test.cpp
Labels: enhancement

#1672 [HAIER_AC176/HAIER_AC_YRW02] Add support A/B unit setting
  src/IRac.cpp
  src/IRac.h
  src/IRsend.h
  src/IRtext.cpp
  src/IRtext.h
  src/IRutils.cpp
  src/ir_Haier.cpp
  src/ir_Haier.h
  src/locale/defaults.h
  test/IRac_test.cpp
  test/ir_Haier_test.cpp
Labels: enhancement

#1680 Moved specifics of Security Policy to github.io page.
  .gitattributes
  SECURITY.md
Labels: Documentation

#1679 [HAIER_AC176] Replace some magic numbers
  test/ir_Haier_test.cpp
Labels: enhancement

#1681 Basic support for Airton Protocol
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/ir_Airton.cpp
  src/locale/defaults.h
  test/ir_Airton_test.cpp
Labels: enhancement

#1677 SamsungAc: Change `clean` setting to a toggle.
  src/IRac.cpp
  src/ir_Samsung.cpp
  src/ir_Samsung.h
  test/IRac_test.cpp
  test/ir_Samsung_test.cpp
Labels: enhancement, Pending Confirmation

#1688 Airton: Add detailed A/C support.
  src/IRac.cpp
  src/IRac.h
  src/IRutils.cpp
  src/IRutils.h
  src/ir_Airton.cpp
  src/ir_Airton.h
  test/IRac_test.cpp
  test/ir_Airton_test.cpp
Labels: enhancement

#1690 Fujitsu: Update supported devices
  src/ir_Fujitsu.h
Labels: Documentation

#1693 TOSHIBA_AC: Add Filter setting support. aka. Pure.
  src/IRac.cpp
  src/IRac.h
  src/ir_Toshiba.cpp
  src/ir_Toshiba.h
  test/IRac_test.cpp
  test/ir_Toshiba_test.cpp
Labels: enhancement

#1666 MITSUBISHI_AC: Added support for i-SAVE mode.
  .gitignore
  src/IRac.cpp
  src/IRtext.cpp
  src/IRtext.h
  src/ir_Mitsubishi.cpp
  src/ir_Mitsubishi.h
  src/locale/defaults.h
  test/IRac_test.cpp
  test/ir_Mitsubishi_test.cpp
Labels: enhancement
