Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2022-10, with the labels that each got.

#1901 Update HA example config for HA 2022.6+
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: Documentation

#1905 Fix poor cut-n-paste error
  src/ir_Sanyo.cpp
Labels: bug

#1906 ARGO: Improve code & add support for decoding 32bit sensor msgs.
  src/IRac.cpp
  src/IRrecv.cpp
  src/IRremoteESP8266.h
  src/ir_Argo.cpp
  src/ir_Argo.h
  test/ir_Argo_test.cpp
Labels: enhancement

#1907 Added Dutch (nl-NL) translation
  src/locale/nl-NL.h
Labels: enhancement, Hacktoberfest, Documentation

#1908 Added Dutch (nl-NL) README
  README_nl.md
Labels: Hacktoberfest, Documentation

#1911 Improve HA MQTT climate handling.
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: bug, enhancement
