Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2022-01, with the labels that each got.

#1726 Confirm we can reproduce `TurnOnFujitsuAC.ino` via IRac/IRMQTTServer.
  test/ir_Fujitsu_test.cpp
Labels: enhancement, Documentation

#1727 Fix library version string calculation.
  src/IRremoteESP8266.h
  test/IRutils_test.cpp
Labels: bug, Documentation

#1731 Add comments to help Teknopoint users.
  src/IRsend.h
  src/ir_Teknopoint.cpp
Labels: Documentation

#1732 ESP32-C3: Work around for some C3 specific compiler issues again.
  src/IRrecv.cpp
Labels: enhancement, ESP32

#1730 Add basic support for HITACHI_AC264 264bit protocol.
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/IRutils.cpp
  src/ir_Hitachi.cpp
  src/ir_Hitachi.h
  src/locale/defaults.h
  test/ir_Hitachi_test.cpp
Labels: enhancement

#1734 MIDEA: Add support for Quiet, Clean & Freeze Protect controls.
  src/IRac.cpp
  src/IRac.h
  src/ir_Midea.cpp
  src/ir_Midea.h
  test/IRac_test.cpp
  test/ir_Midea_test.cpp
Labels: enhancement

#1736 Simplify code based on state_t being initialised by default.
  src/IRac.cpp
  src/IRsend.h
  src/ir_Airton.cpp
  src/ir_Airwell.cpp
  src/ir_Amcor.cpp
  src/ir_Argo.cpp
  src/ir_Carrier.cpp
  src/ir_Coolix.cpp
  src/ir_Corona.cpp
  src/ir_Daikin.cpp
  src/ir_Delonghi.cpp
  src/ir_Ecoclim.cpp
  src/ir_Electra.cpp
  src/ir_Fujitsu.cpp
  src/ir_Goodweather.cpp
  src/ir_Gree.cpp
  src/ir_Haier.cpp
  src/ir_Hitachi.cpp
  src/ir_Kelvinator.cpp
  src/ir_LG.cpp
  src/ir_Mirage.cpp
  src/ir_Mitsubishi.cpp
  src/ir_MitsubishiHeavy.cpp
  src/ir_Neoclima.cpp
  src/ir_Panasonic.cpp
  src/ir_Rhoss.cpp
  src/ir_Samsung.cpp
  src/ir_Sanyo.cpp
  src/ir_Sharp.cpp
  src/ir_Tcl.cpp
  src/ir_Technibel.cpp
  src/ir_Teco.cpp
  src/ir_Toshiba.cpp
  src/ir_Transcold.cpp
  src/ir_Trotec.cpp
  src/ir_Truma.cpp
  src/ir_Vestel.cpp
  src/ir_Voltas.cpp
  src/ir_Whirlpool.cpp
  test/IRac_test.cpp
Labels: enhancement

#1738 LG2: Improve Light toggle msg handling.
  src/ir_LG.cpp
  test/ir_LG_test.cpp
Labels: enhancement

#1735 HITACHI_AC264: Add minimal detailed support.
  src/IRac.cpp
  src/IRac.h
  src/ir_Hitachi.cpp
  src/ir_Hitachi.h
  test/IRac_test.cpp
  test/ir_Hitachi_test.cpp
Labels: enhancement

#1740 IRMQTTServer V1.6.1
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: bug, enhancement

#1746 Make KELON (48 bit) protocol decoding stricter.
  src/ir_Kelon.cpp
  test/ir_Kelon_test.cpp
Labels: bug, enhancement

#1750 Refactor `decodeCOOLIX()` code & add another test case.
  src/ir_Coolix.cpp
  test/ir_Coolix_test.cpp
Labels: enhancement

#1752 Update (un)supported DAIKIN128 devices.
  src/ir_Daikin.h
Labels: Documentation
