Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2022-09, with the labels that each got.

#1871 Add light pause to ESP32
  src/IRrecv.cpp
  src/IRrecv.h
Labels: enhancement

#1874 NEC: Update supported devices
  src/ir_NEC.h
Labels: Documentation

#1873 SAMSUNG: Update supported devices
  src/ir_Samsung.h
Labels: Documentation

#1872 SONY: Update supported devices.
  src/ir_Sony.cpp
Labels: Documentation

#1875 Improve the `_IRREMOTEESP8266_VERSION_VAL` macro
  src/IRremoteESP8266.h
Labels: enhancement, Documentation

#1883 v2.8.4 release
  README.md
  README_de.md
  README_fr.md
  ReleaseNotes.md
  library.json
  library.properties
  src/IRremoteESP8266.h
Labels: Documentation

#1888 Added support for Gorenje cooker hood IR protocol
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/ir_Gorenje.cpp
  src/locale/defaults.h
  test/ir_Gorenje_test.cpp
Labels: enhancement
