Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2022-05, with the labels that each got.

#1788 FUJITSU: Improve handling of 10C Heat mode.
  src/IRsend.h
  src/ir_Fujitsu.cpp
  src/ir_Fujitsu.h
  test/IRac_test.cpp
  test/ir_Fujitsu_test.cpp
Labels: enhancement

#1795 Daikin128: Additional unit test.
  test/ir_Daikin_test.cpp
Labels: enhancement

#1796 Fix #if for DECODE_COOLIX48
  src/ir_Coolix.cpp
Labels: bug

#1800 Voltas: Add link to manual for 122LZF A/C.
  src/ir_Voltas.h
Labels: Documentation

#1803 DAIKIN: Add basic support for 200-bit Daikin protocol.
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/IRutils.cpp
  src/ir_Daikin.cpp
  src/ir_Daikin.h
  src/locale/defaults.h
  test/ir_Daikin_test.cpp
Labels: enhancement

#1805 HAIER_AC160: Add basic support for Haier 160bit protocol.
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/IRutils.cpp
  src/ir_Haier.cpp
  src/ir_Haier.h
  src/locale/defaults.h
  test/ir_Haier_test.cpp
Labels: enhancement, Pending Confirmation

#1798 CARRIER_AC128: Experimental Basic support for Carrier AC 128bit protocol.
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/IRutils.cpp
  src/ir_Carrier.cpp
  src/ir_Carrier.h
  src/locale/defaults.h
  test/ir_Carrier_test.cpp
Labels: enhancement, Pending Confirmation

#1808 DAIKIN: Update supported devices
  src/ir_Daikin.h
Labels: Documentation

#1811 TOTO: An experimental _(s)wipe_ at support for Toto Toilets.
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/ir_Toto.cpp
  src/locale/defaults.h
  test/ir_Toto_test.cpp
Labels: enhancement, Pending Confirmation
