Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2022-03, with the labels that each got.

#1769 IRMQTTServer: add MQTT_SERVER_AUTODETECT_ENABLE
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: enhancement

#1768 [BUG] ESP32-C3: Fix reboot/crashes on ESP32-C3s when receiving.
  examples/DumbIRRepeater/DumbIRRepeater.ino
  examples/IRrecvDemo/IRrecvDemo.ino
  examples/IRrecvDumpV2/IRrecvDumpV2.ino
  examples/IRrecvDumpV3/IRrecvDumpV3.ino
  examples/SmartIRRepeater/SmartIRRepeater.ino
  src/IRrecv.cpp
  src/IRrecv.h
Labels: bug, enhancement, ESP32, Pending Confirmation

#1771 LG: Add Swing Toggle support for Model `LG6711A20083V`
  src/IRac.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/IRtext.h
  src/IRutils.cpp
  src/ir_LG.cpp
  src/ir_LG.h
  src/locale/defaults.h
  test/ir_LG_test.cpp
Labels: enhancement

#1774 MIDEA: Update supported devices
  src/ir_Midea.h
Labels: Documentation

#1758 Support for Hitachi RAS-70YHA3 (remote RAR-3U3)
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/IRutils.cpp
  src/ir_Hitachi.cpp
  src/ir_Hitachi.h
  src/locale/defaults.h
Labels: enhancement

#1776 HITACHI_AC296: Add `IRac` class support & tests.
  src/IRac.cpp
  src/IRac.h
  src/ir_Hitachi.cpp
  src/ir_Hitachi.h
  test/IRac_test.cpp
  test/ir_Hitachi_test.cpp
Labels: enhancement
