Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2023-06, with the labels that each got.

#2002 IRUtils:typeToString() — simplify
  src/IRutils.cpp
Labels: enhancement

#2003 IRac::isProtocolSupported() — do not list WHIRLPOOL_AC unconditionally as supported protocol
  examples/IRrecvDumpV2/platformio.ini
  examples/SmartIRRepeater/platformio.ini
  src/IRac.cpp
Labels: bug, enhancement

#2008 [BUG] Fix missing parameter in call to `IRac::gree()`
  src/IRac.cpp
Labels: bug
