Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2023-01, with the labels that each got.

#1944 Update XMP status to Stable
  src/ir_Xmp.cpp
Labels: Documentation

#1946 Sync the on state to power from mode for HA
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: enhancement

#1940 Examples: IRMQTTServer extended with new A/C common fields
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: enhancement

#1947 IR MQTT Server: HA multi output discovery
  examples/IRMQTTServer/IRMQTTServer.h
  examples/IRMQTTServer/IRMQTTServer.ino
Labels: enhancement

#1945 Experimental basic support for Carrier 84-bit protocol.
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/IRutils.cpp
  src/ir_Carrier.cpp
  src/ir_Carrier.h
  src/locale/defaults.h
  test/IRrecv_test.h
  test/ir_Carrier_test.cpp
Labels: enhancement, Pending Confirmation
