Repository crankyoldgit/IRremoteESP8266, pull requests merged in 2024-07, with the labels that each got.

#2115 Update haier160 & HaierYRWO2 to use quiet in the common class.
  src/IRac.cpp
Labels: bug, enhancement

#2121 Fix `decodeYork()` parameter names & defaults.
  src/IRrecv.h
Labels: enhancement, Documentation

#2094 Add support of Toshiba Remote Control B
  src/IRsend.h
  src/IRtext.cpp
  src/IRtext.h
  src/IRutils.cpp
  src/ir_Toshiba.cpp
  src/ir_Toshiba.h
  src/locale/defaults.h
  test/IRac_test.cpp
  test/ir_Toshiba_test.cpp
Labels: enhancement

#2120 Added support for Bluestar Heavy AC
  src/IRrecv.cpp
  src/IRrecv.h
  src/IRremoteESP8266.h
  src/IRsend.cpp
  src/IRsend.h
  src/IRtext.cpp
  src/IRutils.cpp
  src/ir_BluestarHeavy.cpp
  src/locale/defaults.h
Labels: enhancement
